import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const s=fs.readFileSync('world.html','utf8');for(const m of s.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi))if(!/type=['"](?:module|importmap|application\/json)/.test(m[1])&&m[2].trim())new vm.Script(m[2]);
function fn(name){const start=s.indexOf('function '+name+'('),end=s.indexOf('\nfunction ',start+1);return s.slice(start,end)}
let now=10000;const car={id:'native-car',r:2,c:3,parked:true},a={car,state:'walking_to',tgtR:4,tgtC:5,r:2,c:3,life:60,ang:.4,walkPhase:2,look:{gender:1}},b={...a,look:{gender:0}};
const c={performance:{now:()=>now},Math,Number,CARS:[car],_parkingNpcs:[a,b],_threeVehicleIds:new WeakMap(),_threeNpcIds:new WeakMap(),_threeVehicleIdSeq:0,_threeNpcIdSeq:0,_spawnParkingNpc(){throw Error('collector cannot spawn')}};vm.createContext(c);vm.runInContext(fn('_threeNpcEntityId')+fn('_threeParkingNpcView')+fn('_threeVehicleEntityId')+fn('_tickParkingNpcs'),c);c._tickParkingNpcs._nextT=Infinity;
const collectCode=s.slice(s.indexOf('// PARKING_NPC_SNAPSHOT_START'),s.indexOf('// PARKING_NPC_SNAPSHOT_END'));function collect(existing=[]){c.npcSource=existing;c.combat=[];c.fxNow=now;vm.runInContext(collectCode,c);return c.combat}
const before=JSON.stringify([a,b,car]);let rows=collect();assert.equal(rows.length,2);const idA=c._threeNpcEntityId(rows[0]),idB=c._threeNpcEntityId(rows[1]);assert.notEqual(idA,idB);assert.equal(rows[0]._actionRef,a);assert.equal(rows[0].parkingCarId,'vehicle_native-car');assert.equal(rows[0].moving,true);assert.equal(rows[0].look.gender,1);assert.equal(JSON.stringify([a,b,car]),before,'snapshot does not mutate source state');
c._parkingNpcs.splice(0,1);assert.equal(c._threeNpcEntityId(collect()[0]),idB,'ID survives source index shift');assert.equal(collect([b]).length,0,'no duplicate original NPC');
b.state='idle_at';b.idleUntil=now+500;rows=collect();assert(!rows[0].moving);assert.equal(rows[0].parkingState,'idle_at');b.state='returning';assert.equal(collect()[0].speed,1.5);
b.state='getting_in';b.idleUntil=now+400;assert.equal(collect()[0].parkingEntryProgress,0);now+=200;assert.equal(collect()[0].parkingEntryProgress,.5);now+=201;c._tickParkingNpcs(.001);assert.equal(collect().length,0,'source get-in removes same actor');
c._parkingNpcs.push(b);b.state='sitting';assert.equal(collect().length,0);b.state='walking_to';b.life=0;assert.equal(collect().length,0);b.life=.75;assert.equal(collect()[0].visibilityAlpha,.5);c.CARS.length=0;assert.equal(collect()[0].parkingCarId,null,'stolen car does not keep ghost reference');c._tickParkingNpcs(.01);assert.equal(b.car,null);
const replacement={...b,life:60,car,state:'walking_to'};c._parkingNpcs.splice(0,1,replacement);assert.notEqual(c._threeNpcEntityId(collect()[0]),idB,'new source person cannot reuse prior appearance identity');
console.log('PASS parking NPC collector: real original refs, stable IDs across splice, no duplicates/spawns, sex/look, walk/return/idle/get-in, source removal, sitting/expired invisibility, stolen car ghost rejection');
