import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';
const world=fs.readFileSync('world.html','utf8'),code=fs.readFileSync('assets/maps/city_rebuild_v1/npc_civilian_activity_source.js','utf8');
const fn=name=>{const start=world.indexOf('function '+name+'(');let p=world.indexOf('{',start),d=1;for(p++;d;p++){if(world[p]==='{')d++;if(world[p]==='}')d--;}return world.slice(start,p);};
function fixture(){let now=1000,wall=false,checks=0;const NPCS=[],c={Math,Number,Set,Map,NPCS,player:{r:6,c:5},performance:{now:()=>now},_npcStableUnit:()=>.2,_residentCanSocialize:n=>!n.dead&&!n._civilianActivity,_npcEffectiveSpeed:()=>.44,_npcSpeechSlots:()=>5,_applyNpcConversationEffect(){},_npcConversationFor:(a,b)=>({speaker:a,listener:b,first:'Привет',reply:'Как дела?',effect:'calm'}),_cancelNpcDirectedSearch:n=>{n._routeSearchPending=false;},_civilianPlanCancel:n=>{n._civilianSeat=null;n._civilianPlan={phase:'seek_shop'};}};
 const pass=(r,col)=>{checks++;return r>=1&&r<=20&&col>=1&&col<=20&&!(wall&&r>=5.8&&r<=6.2&&col>=4.5&&col<=5.5);};c.npcPassable=c.npcPassableForSnitch=pass;c._npcRouteWalkBlocked=(r,col)=>!pass(r,col);c._walkNpcNavigationResolver=({r,c:col})=>({blocked:!pass(r,col),depth:0,surface:'land'});
 vm.createContext(c);for(const name of ['_clearNpcRoute','_npcBodyPassable','_npcPathPassable'])vm.runInContext(fn(name),c);vm.runInContext(code,c);
 return {c,actor(id,r=5,col=5){const n={id,r,c:col,hp:80,speed:1,tr:r,tc:col,walking:true,walkPhase:0,_civilianPlan:{phase:'walk_to_shop',doorId:'same-shop',cycle:1}};NPCS.push(n);return n;},now:()=>now,frame(dt=.05){now+=dt*1000;for(const n of NPCS){const before={r:n.r,c:n.c};c._npcPurposefulActivityTick(n,dt,now);assert(Math.hypot(n.r-before.r,n.c-before.c)<=.44*Math.min(.1,dt)+1e-8,'source step remains bounded');}},wall(value){wall=value;},checks:()=>checks};
}
const f=fixture(),a=f.actor('resident_a'),b=f.actor('resident_b',7),plan=a._civilianPlan;f.wall(true);assert(!f.c._npcStartCivilianConversation(a,b,f.now()),'wall/water/object predicate rejects a through-obstacle meeting');assert(!a._civilianActivity);f.wall(false);assert(f.c._npcStartCivilianConversation(a,b,f.now()));assert.equal(a.r,5,'planning never teleports');assert.equal(a._civilianActivity.phase,'approach');
for(let i=0;i<200&&a._civilianActivity?.phase==='approach';i++)f.frame();assert.equal(a._civilianActivity.phase,'active');assert.equal(a._socialPartnerId,b.id);assert.equal(b._socialPartnerId,a.id);f.frame();assert(Math.abs(Math.cos(a.ang-b.ang)+1)<1e-6,'partners face each other');assert.equal(a.hp,80);assert.equal(f.c.NPCS[0],a);
for(let i=0;i<250&&a._civilianActivity;i++)f.frame();assert(!a._civilianActivity&&!b._civilianActivity);assert.equal(a._civilianPlan,plan,'original visit intent survives social pause');assert.equal(a._talking,0);assert.equal(a.idleUntil,0);assert(a._socialCooldownUntil>f.now(),'no immediate endless re-chat');
const block=fixture(),x=block.actor('resident_x'),y=block.actor('resident_y',7);assert(block.c._npcStartCivilianConversation(x,y,block.now()));block.wall(true);for(let i=0;i<80&&x._civilianActivity;i++)block.frame();assert(!x._civilianActivity&&!y._civilianActivity,'new obstacle cancels both reservations');assert(x.r<5.8);
for(const danger of ['dead','snitching','_medicalDowned','_fighting','_corpsePhoneCall','panicUntil']){const h=fixture(),u=h.actor('resident_u'),v=h.actor('resident_v',7);h.c._npcStartCivilianConversation(u,v,h.now());u[danger]=danger==='panicUntil'?h.now()+10000:true;h.frame();assert(!u._civilianActivity&&!v._civilianActivity,danger+' interrupts both');if(danger==='dead')assert(u.dead);}
const playerChat=fixture(),pc=playerChat.actor('resident_playerchat'),pc2=playerChat.actor('resident_playerchat2',7);playerChat.c._npcStartCivilianConversation(pc,pc2,playerChat.now());pc._playerConversationOpen=true;pc._talking=Number.MAX_SAFE_INTEGER;playerChat.frame();assert(!pc._civilianActivity&&!pc2._civilianActivity);assert.equal(pc._talking,Number.MAX_SAFE_INTEGER,'ambient cleanup cannot cancel an opened player conversation');
const reader=fixture(),r=reader.actor('resident_read');r._civilianSeat={id:'real-bench',r:5,c:5};r._civilianPlan={phase:'rest',cycle:1,until:reader.now()+6000};assert(reader.c._npcStartBenchReading(r,reader.now()));assert.equal(reader.c._npcCivilianActivitySnapshot(r).kind,'read');r.snitching=true;reader.frame();assert(!r._civilianSeat&&!r._civilianActivity,'phone interruption releases the real bench');
const smoker=fixture(),s=smoker.actor('resident_smoke');assert(smoker.c._npcStartStandingSmoke(s,smoker.now()));for(let i=0;i<240&&s._civilianActivity;i++)smoker.frame();assert(!s._civilianActivity&&s.idleUntil===0);assert.equal(s.r,5);assert.equal(s._civilianPlan.doorId,'same-shop');
const far=fixture();far.c.player={r:150,c:150};const fa=far.actor('far_a'),fb=far.actor('far_b',7);vm.runInContext('const NPC_SOCIAL_CELL_SIZE=2.4;',far.c);vm.runInContext(fn('_findNpcSocialPair'),far.c);assert.equal(far.c._findNpcSocialPair(far.now()),null,'legacy nearby-only behavior retained');const farPair=far.c._findNpcSocialPair(far.now(),true);assert(farPair&&farPair.includes(fa)&&farPair.includes(fb),'native social plans do not depend on camera proximity');assert(far.c._npcStartCivilianConversation(fa,fb,far.now()));fa.dead=true;far.frame();assert(!fb._civilianActivity,'offscreen threats still interrupt the pair');
const perf=fixture();for(let i=0;i<3;i++){const u=perf.actor('resident_'+i+'a',5,5+i*2),v=perf.actor('resident_'+i+'b',7,5+i*2);perf.c._npcStartCivilianConversation(u,v,perf.now());}for(let i=0;i<100;i++)perf.frame();
const samples=[];for(let i=0;i<200;i++){const t=performance.now();for(let j=0;j<100;j++)for(const n of perf.c.NPCS)perf.c._npcPurposefulActivityTick(n,.016,perf.now());samples.push((performance.now()-t)/100);}samples.sort((a,b)=>a-b);
console.log(JSON.stringify({result:'PASS original IDs, real capsule path, approach/talk/finish, same task resumption, wall/dynamic blocker, death/panic/call cancellation, bench release, smoke return',activityTick6ActorsCpuMs:{p50:samples[100],p95:samples[190]},limits:'isolated source CPU, no city renderer/FPS acceptance'}));
