import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';
const world=fs.readFileSync('world.html','utf8'),helper=fs.readFileSync('assets/maps/city_rebuild_v1/npc_civilian_elapsed_source.js','utf8'),movement=fs.readFileSync('assets/maps/city_rebuild_v1/npc_city_population_source.js','utf8');
const timingStart=world.indexOf('  let dt = (t - prevT) / 1000;'),timing=world.slice(timingStart,world.indexOf('// КРИТИЧНО:',timingStart));
assert(timing.includes('_npcBeginCivilianElapsedFrame(civilianFrameElapsed'));
assert(world.includes('const civilianRoutineDt=_npcConsumeCivilianElapsed(n,dt,now);'));
assert(world.includes('_npcRoutineStep(n,_npcCivilianElapsedEligible(n,now)?civilianRoutineDt:dt,'));
const fn=name=>{const start=world.indexOf('function '+name+'(');assert(start>=0,name);let p=world.indexOf('{',start),d=1;for(p++;d;p++){if(world[p]==='{')d++;if(world[p]==='}')d--;}return world.slice(start,p);};
function fixture(distant=false){
 let clock=1000,blocked=false,sweeps=0;const context={native:true,hidden:false,battle:false,hitStop:false,resuming:false},n={id:'resident_elapsed',r:80,c:80,tr:500,tc:80,speed:10,hp:100,maxHp:100,walkPhase:0,_routineSpeedK:1,_npcSimDue:1000};
 const b={Math,Number,Object,Map,Set,NPCS:[n],document:{hidden:false},_battleOpen:false,hitStopUntil:0,_worldResumeFrames:0,player:{r:distant?0:80,c:distant?0:80},performance:{now:()=>clock},_walkRendererActive:()=>context.native,npcPassable:()=>true,_npcRouteWalkBlocked:()=>false,_walkNpcNavigationResolver:q=>{if(q.mode==='sweep'){sweeps++;return{swept:true,blocked};}return{blocked:false,depth:0,surface:'land'};}};b.npcPassableForSnitch=b.npcPassable;
 vm.createContext(b);vm.runInContext('const NPC_HERO_PACE=Object.freeze({walk:1.8/4.1,run:7.8/4.1});const _npcSimulationStats={full:0,distant:0,deferred:0};',b);for(const name of ['_npcPacedSpeed','_npcEffectiveSpeed','_npcBodyPassable','_npcPathPassable','_npcSimulationDelta'])vm.runInContext(fn(name),b);vm.runInContext(movement,b);vm.runInContext(helper,b);
 vm.runInContext('let prevT=1000;globalThis.actualFrameDelta=t=>{'+timing+'return dt;}',b);
 return{b,n,context,now:()=>clock,blocked(v){blocked=v;},sweeps:()=>sweeps,frame(elapsed,{skip=false,enabled=true}={}){clock+=elapsed*1000;b.document.hidden=context.hidden;b._battleOpen=context.battle;b.hitStopUntil=context.hitStop?clock+1:0;b._worldResumeFrames=context.resuming?1:0;const physics=b.actualFrameDelta(clock);if(skip)return; if(enabled)b._npcAccumulateCivilianElapsed(n,clock);const dt=b._npcSimulationDelta(n,physics,clock);if(!dt)return;const routine=enabled?b._npcConsumeCivilianElapsed(n,dt,clock):dt;if(!b._npcCivilianElapsedEligible(n,clock))return;return b._npcRoutineStep(n,routine,b.npcPassable);}};
}
const speed=[];for(const distant of [false,true])for(const fps of [5,10,20])for(const enabled of [false,true]){const f=fixture(distant);for(let i=0;i<20*fps;i++)f.frame(1/fps,{enabled});const mps=(f.n.r-80)*4.1/20;assert(Math.abs(mps-(enabled?1.8:1.8*Math.min(1,fps*.1)))<.025);speed.push({distant,fps,enabled,mps});}
for(const reason of ['hidden','battle','hitStop','resuming']){
 const f=fixture(true);f.n._npcSimDue=f.now()+200;f.frame(.1);assert(f.n._civilianElapsedDebt>.09);const r=f.n.r;f.context[reason]=true;for(let i=0;i<40;i++)f.frame(.25,{skip:true});assert.equal(f.n.r,r);f.context[reason]=false;f.n._npcSimDue=0;f.frame(.05);assert((f.n.r-r)*4.1<=.09+1e-9);assert((f.n._civilianElapsedDebt||0)<=.05+1e-9,'paused debt is not replayed '+reason);
}
for(const field of ['dead','_fighting','_civilianActivity','_civilianTrip','_residentNativeVisit','_residentIndoors','_uniqueNpc','_empireBoss','_policeCuffed','panicUntil']){
 const f=fixture(true);f.n._npcSimDue=f.now()+200;f.frame(.1);assert(f.n._civilianElapsedDebt>.09);f.n[field]=field==='panicUntil'?f.now()+5000:true;const r=f.n.r;f.frame(.1);assert.equal(f.n.r,r);assert.equal(f.n._civilianElapsedDebt,0);assert((f.n._npcSimCarry||0)<=.1);delete f.n[field];f.frame(.05);assert((f.n.r-r)*4.1<=.09+1e-9,'no prior elapsed on recovery '+field);
}
const long=fixture(true);long.n._npcSimDue=long.now()+200;long.frame(.1);const r=long.n.r;long.frame(30);assert((long.n.r-r)*4.1<=.18+1e-9,'long gap has only legacy capped fallback');assert.equal(long.n._civilianElapsedDebt,0);
const reset=fixture(true);reset.n._npcSimDue=reset.now()+200;reset.frame(.1);reset.b._npcResetCivilianElapsed();const resetR=reset.n.r;reset.frame(.05);assert((reset.n.r-resetR)*4.1<=.09+1e-9);assert((reset.n._civilianElapsedDebt||0)<=.05+1e-9);
const repeated=fixture();repeated.b._npcBeginCivilianElapsedFrame(.2,repeated.context);repeated.b._npcAccumulateCivilianElapsed(repeated.n,1000);repeated.b._npcAccumulateCivilianElapsed(repeated.n,1000);assert.equal(repeated.n._civilianElapsedDebt,.2);
// Threat starts after the admission hook: the final movement call rechecks it.
const late=fixture();late.b._npcBeginCivilianElapsedFrame(.2,late.context);late.b._npcAccumulateCivilianElapsed(late.n,1000);const proposed=late.b._npcConsumeCivilianElapsed(late.n,.1,1000);assert.equal(proposed,.2);late.n.panicUntil=5000;const final=late.b._npcCivilianElapsedEligible(late.n,1000)?proposed:.1;assert.equal(final,.1);assert.equal(late.n._civilianElapsedDebt,0);
const wall=fixture();wall.blocked(true);assert.equal(wall.frame(.2),false);assert.equal(wall.n.r,80);assert(wall.sweeps()>0,'longer segment retains continuous native sweep');
const foreign=fixture();foreign.n.id='police_1';foreign.n._npcSimCarry=.17;foreign.b._npcBeginCivilianElapsedFrame(.2,foreign.context);foreign.b._npcAccumulateCivilianElapsed(foreign.n,1000);assert.equal(foreign.n._npcSimCarry,.17,'nonparticipant shared state untouched');assert.equal(foreign.b._npcConsumeCivilianElapsed(foreign.n,.1,1000),.1);
const legacy=fixture();legacy.context.native=false;legacy.frame(.2);assert(Math.abs((legacy.n.r-80)*4.1-.18)<1e-9,'legacy mode retains capped movement');
// Same 288 calm near residents, same actual speed/body/step, warmed alternation.
const p=fixture(),actors=Array.from({length:288},(_,i)=>({...p.n,id:'resident_perf_'+i,tr:1e6})),baseline=[],candidate=[];
const batch=enabled=>{p.b._npcBeginCivilianElapsedFrame(.05,p.context);for(const n of actors){if(enabled)p.b._npcAccumulateCivilianElapsed(n,1000);const dt=p.b._npcSimulationDelta(n,.05,1000);const walkDt=enabled?p.b._npcConsumeCivilianElapsed(n,dt,1000):dt;if(!enabled||p.b._npcCivilianElapsedEligible(n,1000))p.b._npcRoutineStep(n,walkDt,p.b.npcPassable);}};
for(let i=0;i<100;i++){batch(false);batch(true);}for(let i=0;i<160;i++){let at=performance.now();batch(false);baseline.push(performance.now()-at);at=performance.now();batch(true);candidate.push(performance.now()-at);}
const stats=a=>{a.sort((a,b)=>a-b);return{p50:a[80],p95:a[152]};};console.log(JSON.stringify({pass:true,speed,cpu288Ms:{baseline:stats(baseline),candidate:stats(candidate)},scope:'connected source frame hooks/cadence/speed/body/sweep/step; no full-scene FPS acceptance'},null,2));
