import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';
const world=fs.readFileSync('world.html','utf8'),code=fs.readFileSync('assets/maps/city_rebuild_v1/npc_civilian_activity_source.js','utf8');
const fn=name=>{const start=world.indexOf('function '+name+'(');let p=world.indexOf('{',start),d=1;for(p++;d;p++){if(world[p]==='{')d++;if(world[p]==='}')d--;}return world.slice(start,p);};
function fixture(){let now=1000,terrain='land',depth=0,solid=false,sweeps=0;const NPCS=[],c={Math,Number,Set,Map,NPCS,performance:{now:()=>now},_npcStableUnit:()=>.5,_residentCanSocialize:n=>!n.dead&&!n._civilianActivity,_cancelNpcDirectedSearch(){throw Error('jog must reuse the existing route');},npcCarriedGun:n=>n.gun,_civilianPlanCancel(){},_npcRouteWalkBlocked:()=>false,npcPassable:()=>true};c.npcPassableForSnitch=c.npcPassable;
 c._walkNpcNavigationResolver=q=>{if(q.mode==='sweep'){sweeps++;return{swept:true,blocked:solid};}return{blocked:false,depth,surface:terrain};};
 vm.createContext(c);for(const name of ['_clearNpcRoute','_setNpcRoute','_npcBodyPassable','_npcPathPassable'])vm.runInContext(fn(name),c);vm.runInContext(code,c);
 return{c,actor(id='resident_outdoor'){const n={id,r:5,c:5,hp:100,maxHp:100,walking:true,_routeKind:'walk',_routeIndex:0,_route:[{r:5,c:5.5},{r:5,c:6},{r:5,c:6.5},{r:5,c:7}],_civilianPlan:{phase:'wander',identity:'same-plan'}};NPCS.push(n);return n;},now:()=>now,tick(n,dt=.05){now+=dt*1000;const r=n.r,col=n.c;c._npcPurposefulActivityTick(n,dt,now);assert(Math.hypot(n.r-r,n.c-col)<=2.6/4.1*Math.min(.5,dt)+1e-9);},terrain(v){terrain=v;},depth(v){depth=v;},solid(v){solid=v;},sweeps:()=>sweeps};
}
for(const kind of ['jog','stretch','squat','lookaround']){
 const f=fixture(),n=f.actor(),plan=n._civilianPlan;assert(f.c._npcStartOutdoorRoutine(n,kind,f.now()));assert.equal(n._civilianPlan,plan);let distance=0,previous=n.c,headings=new Set();
 for(let i=0;i<900&&n._civilianActivity;i++){f.tick(n);distance+=Math.abs(n.c-previous);previous=n.c;if(n.walking)headings.add(Math.round(n.ang));}
 assert(!n._civilianActivity);assert(!n._civilianJogRunning);assert.equal(n._civilianPlan,plan);assert.equal(n.hp,100);assert.equal(f.c.NPCS[0],n);
 if(kind==='jog'){assert(distance>3.8,'actual out-and-back journey');assert(Math.abs(n.c-5)<.025);assert(headings.has(0)&&headings.has(3),'heading follows velocity on both legs');assert(f.sweeps()>100);}else assert.equal(distance,0);
}
for(const kind of ['jog','stretch','squat','lookaround'])for(const bad of ['road','water','solid','gun']){const f=fixture(),n=f.actor();if(bad==='road')f.terrain('road');if(bad==='water')f.depth(.3);if(bad==='solid')f.solid(true);if(bad==='gun')n.gun='pistol';assert(!f.c._npcStartOutdoorRoutine(n,kind,f.now()),kind+' excludes '+bad);}
for(const cause of ['dead','panicUntil','_corpsePhoneCall','gun','solid']){const f=fixture(),n=f.actor();f.c._npcStartOutdoorRoutine(n,'jog',f.now());f.tick(n);const pos=n.c;n._paceRunning=true;if(cause==='solid')f.solid(true);else n[cause]=cause==='panicUntil'?f.now()+9000:true;f.tick(n);assert(!n._civilianActivity,cause);assert.equal(n.c,pos);assert(!n._civilianJogRunning);assert(n._paceRunning,'own cleanup preserves panic running');}
const injured=fixture(),old=injured.actor();old._arcKey='oldman';assert(!injured.c._npcStartOutdoorRoutine(old,'squat',injured.now()));assert(injured.c._npcStartOutdoorRoutine(old,'lookaround',injured.now()));
for(const route of [null,undefined,[],{},'route']){const missing=fixture(),unrouted=missing.actor();unrouted._route=route;assert(!missing.c._npcStartOutdoorRoutine(unrouted,'jog',missing.now()),'missing/nonarray route is safely deferred');}
const cadence=fixture(),near=cadence.actor('near'),far=cadence.actor('far');cadence.c._npcStartOutdoorRoutine(near,'jog',cadence.now());cadence.c._npcStartOutdoorRoutine(far,'jog',cadence.now());for(let i=0;i<5;i++)cadence.tick(near,.05);cadence.tick(far,.25);assert(Math.abs(near.c-far.c)<1e-9,'far accumulated delta matches five near steps');assert(Math.abs((far.c-5)*4.1-.65)<1e-9,'same real speed 2.6 m/s');cadence.solid(true);const stopped=far.c;cadence.tick(far,.25);assert.equal(far.c,stopped,'whole larger step remains continuously swept');
const corners=fixture(),fine=corners.actor('fine'),coarse=corners.actor('coarse');corners.c._npcStartOutdoorRoutine(fine,'jog',corners.now());corners.c._npcStartOutdoorRoutine(coarse,'jog',corners.now());for(let batch=0;batch<23;batch++){for(let i=0;i<5;i++)corners.tick(fine,.05);corners.tick(coarse,.25);assert(Math.abs(fine.c-coarse.c)<1e-8,'same progress across every waypoint and turnaround');assert.equal(fine.ang,coarse.ang);}
const scheduled=fixture();scheduled.c._findNpcSocialPair=()=>null;scheduled.c._npcStableUnit=(n,s)=>s==='smoker'?.99:[.2,.5,.7,.9][Number(n.id.slice(1))%4];for(let i=0;i<288;i++)scheduled.actor('n'+i);
for(let i=0;i<50;i++){scheduled.c._npcPurposefulSocialTick(1000+i*1400);const kinds=scheduled.c.NPCS.map(n=>n._civilianActivity?.kind);assert(kinds.filter(k=>k==='jog').length<=3);assert(kinds.filter(k=>k==='stretch'||k==='squat').length<=4);assert(kinds.filter(k=>k==='lookaround').length<=2);}
assert(scheduled.c.NPCS.some(n=>n._civilianActivity?.kind==='jog'));assert(scheduled.c.NPCS.some(n=>n._civilianActivity?.kind==='squat'));assert(scheduled.c.NPCS.some(n=>n._civilianActivity?.kind==='lookaround'));
const perf=fixture(),n=perf.actor();perf.c._npcStartOutdoorRoutine(n,'squat',perf.now());const samples=[];for(let i=0;i<120;i++){const t=performance.now();for(let j=0;j<1000;j++)perf.c._npcPurposefulActivityTick(n,.016,2000);samples.push((performance.now()-t)/1000);}samples.sort((a,b)=>a-b);
console.log(JSON.stringify({pass:true,activityCpuMs:{p50:samples[60],p95:samples[114]},checks:'existing route reused, return heading, full footprint terrain and exact sweep, bounded speed, threat/weapon cancellation, original plans/identity/HP preserved',limits:'isolated CPU, no scene FPS'}));
