import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
import {createNpcNativePerception} from './assets/maps/city_rebuild_v1/npc_native_perception.mjs';
const source=fs.readFileSync('world.html','utf8'),helper=fs.readFileSync('assets/maps/city_rebuild_v1/npc_incident_reactions_source.js','utf8');
const fn=name=>{const start=source.indexOf('function '+name+'(');assert(start>=0,name);let p=source.indexOf('{',start),depth=1;for(p++;depth;p++){if(source[p]==='{')depth++;if(source[p]==='}')depth--;}return source.slice(start,p);};
function setup({wall=false,behind=false,dead=false}={}){
 let now=5000,fights=0;const witness={id:'witness',r:0,c:0,ang:behind?Math.PI:0,hp:60,alive:true,dead,role:'civilian',_arc:{panicMult:1}},corpse={id:'body',r:0,c:2,dead:true,hp:0,deadAt:0};
 const bodies=wall?[{polygonCR:[[.9,-1],[1.1,-1],[1.1,1],[.9,1]],minYM:0,maxYM:3}]:[],perception=createNpcNativePerception({bodiesAt:()=>bodies});
 const c={performance:{now:()=>now},Math,Number,Map,Set,Array,NPCS:[witness,corpse],beachgoers:new Map(),player:{r:0,c:1},myDrivingCarId:'car',_walkNpcPerceptionResolver:perception.query,_policeWorldLineClear:()=>true,_npcLifeEligible:n=>!n.dead,_npcCancelHelping(){},_npcCancelSocial(){},_civilianPlanCancel(){},_clearNpcRoute(n){n._route=null;},_npcSpeechSlots:()=>1,_npcSetLifeState(n,state,time,duration,gesture){n._lifeState=state;n._lifeGesture=gesture;},_npcRememberEvent(){},_npcPanicStyle:()=> 'flee',_npcEffectiveSpeed:()=>1,_npcTriggerFight(){fights++;},NPC_LIFE_STATES:{PANIC:'panic',ALERT:'alert'},NPC_LIFE_EVENT_PRIORITY:{bullet:60,fight:20},document:{documentElement:{dataset:{}}}};
 vm.createContext(c);for(const name of ['_npcStableUnit','_npcPerceptionHeight','_npcPerceptionTargetHeight','_npcCanSeePoint','_npcWitnessAble','_npcCanWitnessEvent','_npcBeginPanic','markNpcSnitch','_npcQueueWitnessCall'])vm.runInContext(fn(name),c);vm.runInContext(helper,c);
 return {c,witness,corpse,advance:ms=>now+=ms,get now(){return now},get fights(){return fights}};
}
for(const settings of [{wall:true},{behind:true},{dead:true}]){const f=setup(settings);f.c._npcCorpseDiscoveryTick(f.now);assert(!f.witness._corpsePhoneCall);assert(!f.c._npcCorpseEmsReported(f.corpse));}
let f=setup();f.c._npcCorpseDiscoveryTick(f.now);assert(f.witness._corpsePhoneCall);assert.equal(f.witness._lifeGesture,'call');assert(!f.c._npcCorpseEmsReported(f.corpse));
const second={...f.witness,id:'second',_corpsePhoneCall:null,c:-.2};f.c.NPCS.push(second);f.advance(250);f.c._npcCorpseDiscoveryTick(f.now);assert(!second._corpsePhoneCall,'one actual caller reserves each death incident');
f.advance(2900);f.c._npcCorpsePhoneTick(f.witness,f.now);assert(!f.c._npcCorpseEmsReported(f.corpse),'elapsed discovery alone does not dispatch before completed call');f.advance(60);f.c._npcCorpsePhoneTick(f.witness,f.now);assert(f.c._npcCorpseEmsReported(f.corpse));assert.equal(f.corpse._corpseEmsIncidentAt,0,'deadAt zero is a valid incident');
f.corpse.deadAt=1;assert(!f.c._npcCorpseEmsReported(f.corpse),'old report cannot authorize a new death incident');
for(const interruption of ['dead','_medicalDowned','_fightingMelee']){f=setup();f.c._npcCorpseDiscoveryTick(f.now);f.witness[interruption]=true;f.advance(4000);f.c._npcCorpsePhoneTick(f.witness,f.now);assert(!f.c._npcCorpseEmsReported(f.corpse));assert(!f.corpse._corpseEmsWitness);assert(!f.witness._corpsePhoneCall);}
for(const pool of ['player','beach']){f=setup();f.c.NPCS.splice(1);if(pool==='player')f.c._playerEmergencyPatient=f.corpse;else f.c.beachgoers.set(f.corpse.id,f.corpse);f.c._npcCorpseDiscoveryTick(f.now);assert(f.witness._corpsePhoneCall,pool+' corpse is visually discoverable');}
f=setup();f.corpse.dead=true;assert.equal(f.c._npcVehicleHijackReleased(f.corpse,{eventId:'dead-event',carId:'car'},f.now).accepted,false);assert(!f.corpse._hijackReaction);assert.equal(f.corpse.hp,0);
f=setup();let id=0;while(f.c._npcStableUnit(f.witness,'hijack:e'+id)<.2)id++;const event={eventId:'e'+id,carId:'car',playerR:0,playerC:1};assert.equal(f.c._npcVehicleHijackReleased(f.witness,event,f.now).decision,'flee');const reaction=f.witness._hijackReaction;f.advance(1000);f.c._npcVehicleHijackReactionTick(f.witness,.05,f.now);assert.equal(f.witness._witnessStage,'escaping');assert(f.witness.snitching);assert.equal(f.c._npcVehicleHijackReleased(f.witness,event,f.now).duplicate,true);assert.equal(f.witness._hijackReaction,reaction);
f=setup();id=0;while(f.c._npcStableUnit(f.witness,'hijack:e'+id)>=.2)id++;f.c._npcVehicleHijackReleased(f.witness,{eventId:'e'+id,carId:'car'},f.now);f.c._npcVehicleHijackRetake=()=>({status:'complete'});f.advance(1000);f.c._npcVehicleHijackReactionTick(f.witness,.05,f.now);assert.equal(f.fights,0,'cannot attack player through occupied vehicle');f.c.myDrivingCarId=null;f.c._npcVehicleHijackReactionTick(f.witness,.05,f.now);assert.equal(f.fights,1,'existing fight begins only after physical/authority exit');
console.log('PASS incident reactions: native polygon LOS/FOV, living witness, real completed phone/dedup/interruption, deathAt0 and player/beach pools; dead driver silence, stable hijack choice, retreat/call, retake ACK before melee');
