// Actual world functions; isolated deterministic dependencies, no game/server boot.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'world.html'),'utf8');
const danger=source.slice(source.indexOf('function _npcSenseNearbyDanger('),source.indexOf('function _npcLifeTick('));
const gang=source.slice(source.indexOf('function updateGangAggression('),source.indexOf('// П1 ──',source.indexOf('function updateGangAggression(')));
function dangerHarness(fn,cars){let scans=0;const seen=[];const CARS=new Proxy(cars,{get(t,k,r){if(k===Symbol.iterator)scans++;return Reflect.get(t,k,r)}}),context={CARS,_npcBeginPanic:(n,now,until,r,c,kind)=>seen.push({r,c,kind}),_npcStableUnit:()=>1,_npcSetLifeState(){},_npcRememberEvent(){},_npcSpeechSlots:()=>0,NPC_LIFE_STATES:{}};vm.createContext(context);vm.runInContext(fn+';this.run=_npcSenseNearbyDanger;',context);return {call:(n={},time=1000)=>context.run({r:1,c:1,_npcMemory:[],...n},time,[]),seen,scans:()=>scans};}
function incoming(fn){const sent=[],fx=[];const context={myDead:false,myMode:'pvp',myGangs:1,performance:{now:()=>1000},_gangFireNextAt:0,CARS:[{gang:true,r:1,c:1}],player:{r:1,c:2},MAP:Array.from({length:5},()=>Array(5).fill(0)),Math:Object.assign(Object.create(Math),{random:()=>.5}),spawnBullet:(...a)=>fx.push(['bullet',...a]),spawnMuzzle:(...a)=>fx.push(['muzzle',...a]),spawnImpact:(...a)=>fx.push(['impact',...a]),addShake:(...a)=>fx.push(['shake',...a]),ws:{send:s=>sent.push(JSON.parse(s))}};vm.createContext(context);vm.runInContext(fn+';updateGangAggression(.016);',context);return {sent,fx};}
const late=Array.from({length:30},()=>({parked:true}));late[29]={r:1,c:1,vr:2};let h=dangerHarness(danger,late);h.call();assert.equal(h.seen.length,1,'late-array nearby car must be noticed');
for(let i=0;i<18;i++)h.call();assert.equal(h.scans(),1,'build index once per life tick, not once per NPC');h.call({},1250);assert.equal(h.scans(),2);
for(const flag of ['parked','_wrecked','_towed']){h=dangerHarness(danger,[{r:1,c:1,vr:2,[flag]:true}]);h.call();assert.equal(h.seen.length,0);}
h=dangerHarness(danger,[{r:1,c:1,vr:1},{r:8,c:8,vr:3}]);h.call();assert.equal(h.seen.length,0);
h=dangerHarness(danger,[{r:0,c:0,vr:2}]);h.call({r:.1,c:.1});assert.equal(h.seen[0].r,0,'valid zero threat origin must not become NPC position');
h=dangerHarness(danger,[{r:1,c:1,vr:2}]);h.call({_npcMemory:[{kind:'vehicle',at:900}]});h.call({panicUntil:2000});assert.equal(h.seen.length,0,'memory and active-panic guards preserved');
const after=incoming(gang);assert.equal(after.sent.length,0,'incoming cosmetic fire must not issue threat/damage commands');assert.equal(after.fx.length,4,'legacy cosmetic animation remains');
if(process.argv[2]){const old=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),before=dangerHarness(old.danger,late);before.call();assert.equal(before.seen.length,0,'pre-fix source demonstrates index defect');const oldShot=incoming(old.gang);assert.equal(oldShot.sent[0].t,'gang_dmg','pre-fix source sends erroneous command');assert.deepEqual(JSON.parse(JSON.stringify(after.fx)),JSON.parse(JSON.stringify(oldShot.fx)),'fix preserves bullet/muzzle/impact/shake cosmetics');}
console.log('PASS NPC incoming threat and spatial traffic: current actual functions; optional old-source regression verified');
