import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const s=fs.readFileSync('world.html','utf8').replace(/\r\n/g,'\n');function fn(n){const a=s.indexOf(`function ${n}(`);assert.ok(a>=0);return s.slice(a,s.indexOf('\n}',a)+2);}
let now=10000,clear=true,pending=true,moved=false;const calls=[];const v={id:'realcar',kind:'police',state:'go_to_scene',_murderFleet:true,x:0,y:0,ang:0,speed:3,_driverCopId:'realcop',payload:{murderIncident:{r:0,c:5}}},cop={id:'realcop',alive:true,hp:100,_transportBoarded:true,_transportVehicleId:'realcar',_transportSeatId:'front_left',_crewSlot:0,x:0,y:0};
const e={Math,Number,String,performance:{now:()=>now},cityCops:[cop],serviceVehicles:[v],_walkRendererActive:()=>true,_vehicleStep:()=>{throw Error('native police must never use legacy movement');},_walkTrafficNavigationResolver:q=>{calls.push(q);if(q.mode==='road-targets')return{points:[{r:0,c:5,angle:0}]};if(q.mode==='route')return pending?{status:'pending'}:{status:'ready',points:[{r:0,c:0},{r:0,c:5}]};return{clear,reason:clear?'':'solid-building'};},_policeCrewBoardPoint:()=>({r:0,c:1}),_moveMurderResponseCop:()=>moved};vm.createContext(e);for(const n of ['_syncPoliceConvoyCop','_seatGroundPoliceCop','_groundPoliceCanDrive','_policeVehicleStep','_advanceGroundPoliceBoarding'])vm.runInContext(fn(n),e);
e._policeVehicleStep(v,.1);assert.equal(v.x,0);assert.equal(v._nativePoliceReason,'route-pending');assert.equal(calls.find(c=>c.mode==='route').reset,true);
now+=120;pending=false;clear=false;e._policeVehicleStep(v,.1);assert.equal(v.x,0,'solid object blocks native movement');assert.equal(v._nativePoliceReason,'solid-building');assert.equal(calls.filter(c=>c.mode==='route').at(-1).reset,false,'route request stable and reset only once');
clear=true;now+=120;e._policeVehicleStep(v,.1);assert.ok(v.x>0);const accepted=v.x;cop.hp=0;e._policeVehicleStep(v,1);assert.equal(v.x,accepted,'driver death stops motion immediately');
cop.hp=100;cop._transportBoarded=false;cop._transportBoardPhase='';now+=10000;e._advanceGroundPoliceBoarding(v,cop,.1,now,false);assert.equal(cop._transportBoarded,false,'blocked walk cannot timeout-teleport into driver seat');
moved=true;e._advanceGroundPoliceBoarding(v,cop,.1,now,false);assert.equal(cop._transportBoardPhase,'enter');assert.equal(cop._transportBoarded,false);now+=700;e._advanceGroundPoliceBoarding(v,cop,.1,now,false);assert.equal(cop._transportBoarded,true);assert.equal(cop.alive,true);assert.equal(cop.id,'realcop');assert.equal(v._driverCopId,'realcop');
console.log('PASS all ground police: native endpoint, pending route, stable request, physical blocked sweep, alive driver gate, no boarding timeout teleport, seated identity retained');
