import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const source=fs.readFileSync('world.html','utf8').replace(/\r\n/g,'\n');const fn=n=>{const a=source.indexOf('function '+n+'(');assert(a>=0);return source.slice(a,source.indexOf('\n}',a)+2);};
function fixture(points=[]){let now=1000,clear=true;const queries=[];const box={Math,Number,Set,performance:{now:()=>now},serviceVehicles:[],CARS:[],cityCops:[],_cityCopId:0,_svcVehId:0,POLICE_RESPONSE_FLEET_SIZE:3,_policeResponseBaysCache:null,_policeDetentionRegistry:[{id:'site',nativeReady:true,stop:{r:0,c:0,angle:0},handoff:{r:1,c:0},intake:{r:2,c:0},release:{r:2,c:0}}],_walkRendererActive:()=>true,_walkTrafficNavigationResolver:q=>{queries.push(q);return q.mode==='road-targets'?{points}:{clear};},_seatGroundPoliceCop:()=>{},_serviceVehicleFootprintClear:()=>true};vm.createContext(box);for(const n of ['_policeBayOutsideCustody','_policeInitialBayAdmit','_policeResponseBays','_ensurePoliceResponseFleet','spawnPoliceCar'])vm.runInContext(fn(n),box);return{box,queries,advance:()=>now+=251,setClear:x=>clear=x};}
const p=(r,c,angle=0)=>({r,c,angle});
for(const count of [0,1,3]){const f=fixture([p(0,5,Math.PI/2),p(0,8,Math.PI),p(-4,8,.25)].slice(0,count));f.box._ensurePoliceResponseFleet();assert.equal(f.box.serviceVehicles.length,count);for(const v of f.box.serviceVehicles){assert.equal(v.homeR,v.y);assert.equal(v.homeC,v.x);assert.equal(v.ang,v.homeAngle);assert.equal(v.ang,f.box._policeResponseBaysCache.find(b=>b.r===v.y&&b.c===v.x).angle);}const before=JSON.stringify(f.box.serviceVehicles);f.advance();f.box._ensurePoliceResponseFleet();assert.equal(JSON.stringify(f.box.serviceVehicles),before,'repeat never stacks or relocates existing cars');}
{const f=fixture([p(0,5,Math.PI/2)]);f.setClear(false);f.box._ensurePoliceResponseFleet();assert.equal(f.box.serviceVehicles.length,0);f.setClear(true);f.advance();f.box._ensurePoliceResponseFleet();assert.equal(f.box.serviceVehicles.length,1);const q=f.queries.filter(q=>!q.mode).at(-1);assert.deepEqual(q.from,q.to);assert.equal(q.from.angle,Math.PI/2);assert.equal(q.halfLength,1.25);assert.equal(q.halfWidth,.6);}
{const f=fixture([p(0,5)]);f.box.CARS.push({r:0,c:5});f.box._ensurePoliceResponseFleet();assert.equal(f.box.serviceVehicles.length,0);f.box.CARS=[];f.advance();f.box._ensurePoliceResponseFleet();assert.equal(f.box.serviceVehicles.length,1);}
{const f=fixture([p(0,5)]);f.box._walkTrafficNavigationResolver=null;f.box._ensurePoliceResponseFleet();assert.equal(f.box.serviceVehicles.length,0);f.box.spawnPoliceCar(20,20);assert.equal(f.box.serviceVehicles.length,0,'native pending never falls back to legacy police island');}
{const f=fixture([p(0,0),p(2,3),p(2,4)]);const bays=f.box._policeResponseBays();assert.equal(bays.length,0,'clearance includes intake/release corridor plus complete vehicle radius, not only stop');}
{const f=fixture([p(0,5,Math.PI/2),p(0,8,Math.PI)]);f.box.spawnPoliceCar(20,20);f.box.spawnPoliceCar(30,30);f.box.spawnPoliceCar(40,40);assert.equal(f.box.serviceVehicles.length,2);assert.equal(f.box.serviceVehicles[0].ang,Math.PI/2);assert.equal(f.box.serviceVehicles[0].homeC,5);assert.equal(f.box.cityCops.length,4,'admitted response car retains real crew creation');}
{const f=fixture([]);f.box._ensurePoliceResponseFleet();const n=f.queries.length;for(let i=0;i<10000;i++)f.box._ensurePoliceResponseFleet();assert.equal(f.queries.length,n,'unready fleet query throttled to once per250ms');}
const f=fixture([p(0,5)]),times=[];f.box._ensurePoliceResponseFleet();for(let w=0;w<120;w++){const start=performance.now();for(let i=0;i<1000;i++)f.box._ensurePoliceResponseFleet();if(w>=20)times.push((performance.now()-start)/1000);}times.sort((a,b)=>a-b);console.log('PASS police initial admission:0/1/3bays, angle/home, blocked/busy/repeat, unavailable native, corridor, bank crew, bounded retry');console.log(JSON.stringify({scenario:'partial fleet waiting between250ms retries; CPU only',p50Ms:times[50],p95Ms:times[95]}));

