import fs from 'node:fs';
import {registerHooks} from 'node:module';
import {pathToFileURL} from 'node:url';
import {performance} from 'node:perf_hooks';
const root=new URL('../../',import.meta.url),dir=new URL('assets/maps/city_rebuild_v1/',root);
const baseline=process.argv.includes('--baseline'),name=baseline?'baseline':'current';
const {createWindowedBuildingEntry}=await import(new URL((baseline?'interior_qa_baseline/':'')+'building_window_integration.mjs',dir));
const {resolveBuildingPurpose}=await import(new URL('building_interior_purpose.mjs',dir));
const vendor='D:/codex_release/artist13_hero_first_DEV_20260907/demo/vendor/';
registerHooks({resolve(s,c,n){return n(s==='three'?pathToFileURL(vendor+'build/three.module.js').href:s,c)}});
const T=await import(pathToFileURL(vendor+'build/three.module.js')),{GLTFLoader}=await import(pathToFileURL(vendor+'addons/loaders/GLTFLoader.js'));
const placement=JSON.parse(fs.readFileSync(new URL((baseline?'interior_qa_baseline/':'')+'buildings_placement.v1.json',dir))),sources=new Map(),scene=new T.Scene(),active=[],results=[];
for(const item of placement.instances){if(sources.has(item.binding.url))continue;const bytes=fs.readFileSync(new URL(item.binding.url.slice(1),root));const loader=new GLTFLoader().register(()=>({name:'CPU_GEOMETRY_AUDIT',loadTexture:()=>Promise.resolve(new T.Texture())}));sources.set(item.binding.url,(await loader.parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene)}
const started=performance.now();
for(const item of placement.instances){
 const group=new T.Group(),visual=sources.get(item.binding.url).clone(true),t=item.transform;
 visual.traverse(n=>{if(item.hideNodeNames?.includes(n.name))n.visible=false});visual.position.fromArray(t.modelLocalOffsetM);group.add(visual);group.position.fromArray(t.positionM);group.rotation.y=t.yawDegrees*Math.PI/180;group.scale.setScalar(t.uniformScale);scene.add(group);group.updateMatrixWorld(true);
 const start=performance.now(),applied=createWindowedBuildingEntry({THREE:T,visual,instance:item}),entry=applied.entry,interior=entry?.interiorDesign,st=entry?.storeys;
 let draws=0,triangles=0,parts=0;interior?.root.traverse(n=>{if(!n.isMesh)return;draws++;triangles+=(n.geometry.index?.count??n.geometry.attributes.position.count)/3*(n.isInstancedMesh?n.count:1);parts+=n.isInstancedMesh?n.count:1});
 results.push({id:item.id,assetId:item.assetId,purpose:resolveBuildingPurpose(item),creationMs:performance.now()-start,floors:st?.floors.map(f=>({...f,area:(f.rect[2]-f.rect[0])*(f.rect[3]-f.rect[1])})),rooms:interior?.rooms,stairs:st?.stairs.length,metrics:interior?.report,draws,triangles,parts,colliders:entry?.getCollisionBodies().length});active.push({group,...applied});
}
const total={buildings:results.length,floors:results.reduce((n,r)=>n+r.floors.length,0),rooms:results.reduce((n,r)=>n+r.rooms.length,0),stairs:results.reduce((n,r)=>n+r.stairs,0),furniture:results.reduce((n,r)=>n+r.metrics.furniture,0),furnishedRooms:results.reduce((n,r)=>n+r.metrics.furnishedRooms,0),parts:results.reduce((n,r)=>n+r.parts,0),draws:results.reduce((n,r)=>n+r.draws,0),triangles:results.reduce((n,r)=>n+r.triangles,0),colliders:results.reduce((n,r)=>n+r.colliders,0),constructionMs:performance.now()-started};
const out=new URL('outputs/interior_rebuild_20260912/',root);fs.mkdirSync(out,{recursive:true});fs.writeFileSync(new URL(name+'_runtime.json',out),JSON.stringify({scenario:'All 75 actual native GLBs/transforms, all floors; CPU construction and geometry inventory, no GPU/FPS claim',total,buildings:results},null,2));
console.log(JSON.stringify({name,...total}));
if(!baseline&&process.argv.includes('--write-manifest')){const {interiorSafeTargets}=await import(new URL('interior_safe_registry.mjs',dir));const safes=interiorSafeTargets.getTargets().map(({id,buildingId,roomId,purpose,position})=>({id,buildingId,roomId,purpose,position})).sort((a,b)=>a.id.localeCompare(b.id));fs.writeFileSync(new URL('interior_safe_manifest.v1.json',dir),JSON.stringify({version:1,source:'Actual constructed native buildings and room placements; generated by tools/interior_rebuild/audit_runtime.mjs --write-manifest',safes},null,2)+'\n');console.log(JSON.stringify({nativeSafeManifest:safes.length}))}
for(const a of active){a.roomReveals?.dispose();a.entry?.dispose();a.windows?.dispose();a.group.removeFromParent()}
