import fs from 'node:fs';
import {performance} from 'node:perf_hooks';
import {createPedestrianAccessPlan} from '../../assets/maps/city_rebuild_v1/city_pedestrian_access_plan.mjs';
import {createLandscapePlan} from '../../assets/maps/city_rebuild_v1/landscape_plan.mjs';
import {createExplorationRailwayPlan} from '../../assets/maps/city_rebuild_v1/exploration_railway_plan.mjs';
const out='outputs/roads_logical_20260912/',snapshot=JSON.parse(fs.readFileSync(out+(process.argv[2]||'shared_plan_snapshot.json'))),topology=JSON.parse(fs.readFileSync('assets/maps/city_rebuild_v1/topology_for_placement.json')),railPlan=createExplorationRailwayPlan({topology,landscape:createLandscapePlan()}),start=performance.now();
const access=createPedestrianAccessPlan({topology,instances:[...snapshot.buildings,...snapshot.authoredDecor],extraBodies:[...snapshot.decorPlan.colliders,...snapshot.roadPlan.colliders,...snapshot.parkingPlan.colliders],railPlan}),buildMs=performance.now()-start,checks=[];
for(const crossing of snapshot.roadPlan.trafficPlan.crosswalks){const endpoints=crossing.endpoints.map(p=>{const route=access.routeToEntrance(p),sidewalk=access.sidewalkCorridor(p);return {point:p,dryWalkable:access.clear(p.x,p.z),route,sidewalk};}),a=snapshot.roadPlan.junctionRules.flatMap(j=>j.approaches).find(a=>a.id===crossing.approachId),behind=(a.stopPoint.x-crossing.center.x)*crossing.tx+(a.stopPoint.z-crossing.center.z)*crossing.tz,storedRouteFailures=[];for(const [side,landing]of (crossing.walkingAccess||[]).entries())for(const kind of ['doorRoute','sidewalk']){const route=landing[kind];for(let i=1;i<(route?.points.length||0);i++)if(!access.segmentClear(route.points[i-1],route.points[i])){storedRouteFailures.push({side,kind,segment:i,from:route.points[i-1],to:route.points[i]});break;}}checks.push({id:crossing.id,approachId:a.id,rule:a.rule,signalId:a.signalId,signalControl:crossing.signalControl,stopBeforeZebraMetres:behind-1.25,endpoints,storedRouteFailures});}
const report={status:checks.every(c=>c.endpoints.every(e=>e.dryWalkable&&e.sidewalk)&&c.endpoints.some(e=>e.route)&&!c.storedRouteFailures.length&&c.stopBeforeZebraMetres>=.5)?'PASS':'CROSSWALK_ACCESS_GAPS',snapshotCreatedAt:snapshot.createdAt,buildMs,totalMs:performance.now()-start,stats:access.stats,crossings:checks.length,directDoorEndpoints:checks.flatMap(c=>c.endpoints).filter(e=>e.route).length,doorLinkedCrossings:checks.filter(c=>c.endpoints.some(e=>e.route)).length,storedRouteFailures:checks.flatMap(c=>c.storedRouteFailures.map(f=>({crosswalkId:c.id,...f}))),checks};fs.writeFileSync(out+(process.argv[3]||'crosswalk_access_audit.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,checks:undefined},null,2));
