import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {CITY_ROAD_ROUTES} from '../../assets/maps/city_rebuild_v1/city_road_dressing_routes.mjs';
import {createCarWorld} from '../../assets/maps/city_rebuild_v1/car_drive.mjs';
import {createLandscapePlan} from '../../assets/maps/city_rebuild_v1/landscape_plan.mjs';
import {createExplorationRailwayPlan} from '../../assets/maps/city_rebuild_v1/exploration_railway_plan.mjs';
const dir='outputs/roads_logical_20260912/',input=process.argv[2]||dir+'integration_candidate_snapshot.json',bytes=fs.readFileSync(input),s=JSON.parse(bytes),topology=JSON.parse(fs.readFileSync('assets/maps/city_rebuild_v1/topology_for_placement.json')),m=4.1,startTime=performance.now(),crosswalks=s.roadPlan.trafficPlan.crosswalks,rects=s.parkingPlan.surfaceRects,dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const inRect=(p,r)=>p.x>=r.minX&&p.x<=r.maxX&&p.z>=r.minZ&&p.z<=r.maxZ,parkingAt=p=>rects.some(r=>inRect(p,r)),tile=p=>topology.grid[Math.floor(p.z/m)]?.[Math.floor(p.x/m)],roadAt=p=>!!topology.roadMask[Math.floor(p.z/m)]?.[Math.floor(p.x/m)]&&[0,19].includes(tile(p)),publicRoadAt=p=>roadAt(p)&&!parkingAt(p);
const roadSegments=CITY_ROAD_ROUTES.flatMap(road=>road.fragments.flatMap((f,fragment)=>f.slice(1).map((q,i)=>{const p=f[i],a={x:p[0]*m,z:p[1]*m},b={x:q[0]*m,z:q[1]*m},length=dist(a,b);return {roadId:road.id,kind:road.kind,width:road.width,fragment,a,b,length,tx:(b.x-a.x)/length,tz:(b.z-a.z)/length}})));
const cross=(a,b)=>a.x*b.z-a.z*b.x;
const approachById=new Map(s.roadPlan.junctionRules.flatMap(j=>j.approaches).map(a=>[a.id,a]));
function nearestCrosswalks(p,roadId=null){return crosswalks.map(c=>({id:c.id,roadId:approachById.get(c.approachId)?.roadId,distance:dist(c.center,p),junctionId:c.junctionId,approachId:c.approachId,center:c.center,ends:c.endpoints.map(({x,z})=>({x,z})),signalControl:c.signalControl})).filter(c=>!roadId||c.roadId===roadId).sort((a,b)=>a.distance-b.distance).slice(0,3);}
function intersection(a,b,c,d){const u={x:b.x-a.x,z:b.z-a.z},v={x:d.x-c.x,z:d.z-c.z},delta={x:c.x-a.x,z:c.z-a.z},den=cross(u,v);if(Math.abs(den)<1e-7)return null;const t=cross(delta,v)/den,k=cross(delta,u)/den;if(t<0||t>1||k<0||k>1)return null;return{x:a.x+t*u.x,z:a.z+t*u.z,t};}
function inCrosswalk(p,c){const a=c.endpoints[0],b=c.endpoints[1],len=dist(a,b),tx=(b.x-a.x)/len,tz=(b.z-a.z)/len,dx=p.x-a.x,dz=p.z-a.z,along=dx*tx+dz*tz,side=dx*tz-dz*tx;return along>=-.2&&along<=len+.2&&Math.abs(side)<=1.25;}
function dense(points){const out=[];let length=0;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],len=dist(a,b),n=Math.max(1,Math.ceil(len/.2));for(let j=i===1?0:1;j<=n;j++)out.push({x:a.x+(b.x-a.x)*j/n,z:a.z+(b.z-a.z)*j/n,distance:length+len*j/n});length+=len}return out;}
const routes=s.parkingPlan.walkingRoutes.map(route=>{const points=dense(route.points),roadRuns=[],ignored=[];for(let i=0;i<points.length;i++){if(!publicRoadAt(points[i]))continue;const begin=i;while(i+1<points.length&&publicRoadAt(points[i+1]))i++;const end=i,before=points[begin-1],after=points[end+1],events=[];
  if(!before||!after){ignored.push({reason:'route_starts_or_ends_on_carriageway',start:points[begin],end:points[end]});continue;}
  for(const road of roadSegments){const signed=p=>(p.x-road.a.x)*-road.tz+(p.z-road.a.z)*road.tx;
   // Both shores must actually be on opposite sides. Include earlier/later
   // dry points when a private driveway reaches the road centreline.
   const dryBefore=points.slice(Math.max(0,begin-80),begin).filter(p=>!publicRoadAt(p)&&Math.abs(signed(p))>.75),dryAfter=points.slice(end+1,Math.min(points.length,end+81)).filter(p=>!publicRoadAt(p)&&Math.abs(signed(p))>.75),a=dryBefore.at(-1),b=dryAfter[0];if(!a||!b||signed(a)*signed(b)>=0)continue;
   for(let k=begin;k<=end+1;k++){const p=intersection(points[k-1],points[k],road.a,road.b);if(!p||!publicRoadAt(p))continue;const nearA=(a.x-p.x)*road.tx+(a.z-p.z)*road.tz,nearB=(b.x-p.x)*road.tx+(b.z-p.z)*road.tz;if(Math.abs(nearA)>80||Math.abs(nearB)>80)continue;
    if(events.some(e=>e.roadId===road.roadId&&dist(e.point,p)<2))continue;const mapped=crosswalks.filter(c=>inCrosswalk(p,c)).map(c=>c.id);events.push({roadId:road.roadId,roadKind:road.kind,point:{x:p.x,z:p.z,r:p.z/m,c:p.x/m},shoreBefore:{x:a.x,z:a.z},shoreAfter:{x:b.x,z:b.z},signedShoreDistances:[signed(a),signed(b)],mappedCrosswalkIds:mapped,nearestCrosswalkOnSameRoad:nearestCrosswalks(p,road.roadId)[0]||null});
   }
  }
  if(!events.length){ignored.push({reason:'same_bank_or_longitudinal_carriageway_walk',start:before,end:after,roadDistance:points[end].distance-points[begin].distance});continue;}
  const midpoint={x:(before.x+after.x)/2,z:(before.z+after.z)/2},unmarked=events.filter(e=>!e.mappedCrosswalkIds.length),nearest=nearestCrosswalks(midpoint);
  roadRuns.push({entry:before,exit:after,roadDistance:points[end].distance-points[begin].distance,events,unmarkedCrossing:unmarked.length>0,wholeRunInsideMappedZebra:points.slice(begin,end+1).every(p=>crosswalks.some(c=>inCrosswalk(p,c))),nearestCrosswalks:nearest});
 }
 return {lotId:route.lotId,buildingId:route.buildingId,distance:route.distance,points:route.points,trueRoadTraversals:roadRuns,ignoredRoadRuns:ignored};});

// Read-only candidate reroute: existing asphalt may be walked only inside a
// mapped zebra or actual parking/driveway surface. Never paint or alter plans.
const bodies=[...s.buildings,...s.authoredDecor].flatMap(i=>i.collision?.worldBodies||[]).concat(s.decorPlan.colliders,s.roadPlan.colliders,s.parkingPlan.colliders),walker=createCarWorld(topology,bodies,m),rail=createExplorationRailwayPlan({topology,landscape:createLandscapePlan()}),step=m/4,cols=topology.grid[0].length*4,rows=topology.grid.length*4,total=cols*rows,state=new Uint8Array(total),offsets=[[0,0],[.38,0],[-.38,0],[0,.38],[0,-.38]],point=id=>({x:(id%cols+.5)*step,z:(Math.floor(id/cols)+.5)*step});
function allowed(p){for(const [dx,dz]of offsets){const q={x:p.x+dx,z:p.z+dz},r=Math.floor(q.z/m),c=Math.floor(q.x/m),t=topology.grid[r]?.[c];if(![0,8,9,19].includes(t)||topology.protectedMask?.[r]?.[c]||topology.policeMask?.[r]?.[c]||!walker(q.x,q.z)||roadAt(q)&&!parkingAt(q)&&!crosswalks.some(c=>inCrosswalk(q,c)))return false;}return !rail.blocksPlacement(p.x,p.z,.4);}
function cellClear(id){if(id<0||id>=total)return false;if(!state[id])state[id]=allowed(point(id))?1:2;return state[id]===1;}
function edge(a,b){const n=Math.max(1,Math.ceil(dist(a,b)/.3));for(let i=0;i<=n;i++)if(!allowed({x:a.x+(b.x-a.x)*i/n,z:a.z+(b.z-a.z)*i/n}))return false;return true;}
function seeds(p){const r=Math.floor(p.z/step),c=Math.floor(p.x/step),out=[];for(let dr=-2;dr<=2;dr++)for(let dc=-2;dc<=2;dc++){const rr=r+dr,cc=c+dc;if(rr<0||rr>=rows||cc<0||cc>=cols)continue;const id=rr*cols+cc,q=point(id),d=dist(p,q);if(d<2.6&&cellClear(id)&&edge(p,q))out.push({id,d});}return out.sort((a,b)=>a.d-b.d).slice(0,4);}
function routeExisting(from,to){const starts=seeds(from),goals=new Map(seeds(to).map(s=>[s.id,s.d]));if(!starts.length||!goals.size)return {status:'endpoint_not_supported_by_dry_proxy',startSeeds:starts.length,endSeeds:goals.size};
 const heap=[],g=new Map(),parent=new Map();const push=n=>{let i=heap.push(n)-1;while(i){const p=(i-1)>>1;if(heap[p].f<=n.f)break;heap[i]=heap[p];i=p;}heap[i]=n;},pop=()=>{const n=heap[0],last=heap.pop();if(heap.length){let i=0;while(i*2+1<heap.length){let c=i*2+1;if(c+1<heap.length&&heap[c+1].f<heap[c].f)c++;if(heap[c].f>=last.f)break;heap[i]=heap[c];i=c;}heap[i]=last;}return n;};
 for(const seed of starts){g.set(seed.id,seed.d);parent.set(seed.id,-1);push({id:seed.id,g:seed.d,f:seed.d+dist(point(seed.id),to)});}let expanded=0;
 while(heap.length&&expanded<24000){const n=pop();if(n.g!==g.get(n.id))continue;expanded++;if(goals.has(n.id)){const points=[to];let id=n.id;while(id!==-1){points.push(point(id));id=parent.get(id)}points.push(from);points.reverse();return {status:'verified_via_existing_crosswalks',length:n.g+goals.get(n.id),expanded,crosswalkIds:crosswalks.filter(c=>points.some(p=>roadAt(p)&&inCrosswalk(p,c))).map(c=>c.id),points};}if(n.g>=300)continue;const r=Math.floor(n.id/cols),c=n.id%cols,p=point(n.id);for(const id of[c?n.id-1:-1,c<cols-1?n.id+1:-1,r?n.id-cols:-1,r<rows-1?n.id+cols:-1]){if(id<0||!cellClear(id))continue;const next=n.g+step;if(next>=(g.get(id)??Infinity)||!edge(p,point(id)))continue;g.set(id,next);parent.set(id,n.id);push({id,g:next,f:next+dist(point(id),to)});}}
 return {status:expanded>=24000?'search_budget_reached':'no_existing_zebra_route_within_300m',expanded};}
for(const r of routes.filter(r=>r.trueRoadTraversals.some(t=>t.unmarkedCrossing))){const result=routeExisting(r.points[0],r.points.at(-1));if(result.status==='verified_via_existing_crosswalks'&&!result.crosswalkIds.length)result.status='verified_dry_reroute_without_road_crossing';r.existingCrosswalkReroute={...result,addedDistance:result.length===undefined?null:result.length-r.distance};}
const trueRoutes=routes.filter(r=>r.trueRoadTraversals.length),unmarkedRoutes=trueRoutes.filter(r=>r.trueRoadTraversals.some(t=>t.unmarkedCrossing)),report={status:'READ_ONLY_PARKING_WALK_CROSSING_REVIEW',input,inputSHA256:createHash('sha256').update(bytes).digest('hex'),inputStable:fs.readFileSync(input).equals(bytes),elapsedMs:performance.now()-startTime,scope:{buildings:s.buildings.length,lots:s.parkingPlan.lots.length,walkingRoutes:routes.length,crosswalks:crosswalks.length},counts:{routesWithTrueOppositeBankCrossing:trueRoutes.length,oppositeBankRoadRuns:trueRoutes.reduce((n,r)=>n+r.trueRoadTraversals.length,0),routesCrossingOutsideMappedZebra:unmarkedRoutes.length,unmarkedRoadRuns:unmarkedRoutes.reduce((n,r)=>n+r.trueRoadTraversals.filter(t=>t.unmarkedCrossing).length,0),verifiedReroutesViaExistingCrosswalks:unmarkedRoutes.filter(r=>r.existingCrosswalkReroute.status==='verified_via_existing_crosswalks').length,proxyEndpointFailures:unmarkedRoutes.filter(r=>r.existingCrosswalkReroute.status==='endpoint_not_supported_by_dry_proxy').length,noExistingZebraRoute:unmarkedRoutes.filter(r=>r.existingCrosswalkReroute.status==='no_existing_zebra_route_within_300m').length,sameBankRoadRuns:routes.reduce((n,r)=>n+r.ignoredRoadRuns.length,0)},method:['Densify saved walks at ≤.2m. Native roadMask/grid asphalt only; actual lot and driveway rectangles are excluded, not broad road-support/access reservation rectangles.','A genuine road crossing requires an intersection with an authored road centreline and dry points on opposite shores, separated by >.75m signed distance. Same-bank longitudinal road walks are reported separately and excluded from crossing counts.','Mapped-zebra match is geometric against the painted 2.5m-wide crossing span; road-centreline events and whole asphalt traversals are both recorded.','Reroute is read-only A* at1.025m, physical .38m five-point stencil, final authored/procedural/road/parking bodies and rail; asphalt allowed only on the 51 existing crossing spans or private parking/driveway surfaces. Search limit300m/24000 expanded nodes per affected route.'],routes,limits:['No production plan, geometry, NPC runtime or crossing cap is changed.','Shared conservative building bodies are used. An endpoint-proxy failure requires actual entry API review and is not proof of a blocked playable doorway.','Nearest crossing distance alone is not access proof; only successful physical reroutes are marked verified.','No GPU/FPS scene was run.']};
report.counts.verifiedDryReroutesWithoutRoadCrossing=unmarkedRoutes.filter(r=>r.existingCrosswalkReroute.status==='verified_dry_reroute_without_road_crossing').length;
report.counts.serviceAlleyOnlyRoadRuns=trueRoutes.flatMap(r=>r.trueRoadTraversals).filter(t=>t.events.every(e=>e.roadKind==='alley_or_service')).length;
report.counts.publicCarriagewayRunsExcludingServiceAlleys=trueRoutes.flatMap(r=>r.trueRoadTraversals).filter(t=>t.events.some(e=>e.roadKind!=='alley_or_service')).length;
report.counts.unmarkedPublicCarriagewayRunsExcludingServiceAlleys=trueRoutes.flatMap(r=>r.trueRoadTraversals).filter(t=>t.events.some(e=>e.roadKind!=='alley_or_service'&&!e.mappedCrosswalkIds.length)).length;
report.limits.push('A nearest crossing on the same authored road is recorded per centreline event; proximity still does not prove a usable continuous sidewalk. Service alleys are explicitly counted separately.');
fs.writeFileSync(dir+'parking_walk_crossings_raw.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,routes:undefined},null,2));
const round=n=>Number(n.toFixed(1)),short=id=>id.replace('REBUILD-VISUAL-','');
const successful=unmarkedRoutes.filter(r=>r.existingCrosswalkReroute.status.startsWith('verified_'));
const candidate={status:'READ_ONLY_NOT_APPLIED',sourceSHA256:report.inputSHA256,routes:successful.map(r=>({buildingId:r.buildingId,lotId:r.lotId,originalDistance:r.distance,...r.existingCrosswalkReroute})),limitations:report.limits};
fs.writeFileSync(dir+'parking_walk_existing_crosswalk_candidates.json',JSON.stringify(candidate,null,2)+'\n');
const reportRows=unmarkedRoutes.map(r=>{const events=r.trueRoadTraversals.flatMap(t=>t.events).filter(e=>!e.mappedCrosswalkIds.length&&e.roadKind!=='alley_or_service'),coords=events.map(e=>`${e.roadId}: r${e.point.r.toFixed(3)} c${e.point.c.toFixed(3)}`).join('; '),nearest=events.map(e=>e.nearestCrosswalkOnSameRoad?`${e.roadId} → ${e.nearestCrosswalkOnSameRoad.id} (${round(e.nearestCrosswalkOnSameRoad.distance)} м)`:`${e.roadId}: нет зебры на этой дороге`).join('; '),rr=r.existingCrosswalkReroute,result=rr.status==='verified_via_existing_crosswalks'?`Обход: ${rr.crosswalkIds.join(', ')}, Δ${round(rr.addedDistance)} м`:rr.status==='verified_dry_reroute_without_road_crossing'?`Сухой обход без дороги, Δ${round(rr.addedDistance)} м`:'В пределах поиска обход не найден';return`| ${short(r.buildingId)} | ${coords} | ${nearest} | ${result} |`;});
fs.writeFileSync(dir+'parking_walk_crossings_raw.md',`# Пешие маршруты парковка → дверь: read-only аудит\n\nИсточник: ${input}, SHA256 ${report.inputSHA256}; стабильность источника подтверждена. 78 зданий, 39 парковок, 46 сохранённых пеших маршрутов, 51 существующая зебра.\n\n34 маршрута переходят общую дорогу вне зебры. У них 44 непрерывных немаркированных участка проезжей части; ещё один участок только служебного переулка учитывается отдельно. Парковочные и подъездные surfaceRects исключены. 11 продольных либо однобережных выходов на асфальт исключены из количества переходов. Несколько дорожных ID могут описывать один общий асфальтовый коридор: отдельная зебра на каждый такой ID не предлагается.\n\n7 маршрутов имеют проверенный альтернативный путь через существующие зебры, ещё 2 можно проложить по сухой стороне вообще без перехода. Точки всех 9 кандидатов сохранены в parking_walk_existing_crosswalk_candidates.json, но не применены. Для 25 маршрутов поиск не нашёл пути до 300 м; это ограниченный A* по сетке 1.025 м и финальным консервативным коллизиям, а не доказательство отсутствия любого возможного пути. Проверка занимает ${round(report.elapsedMs)} мс CPU; GPU и FPS общей сцены не измерялись.\n\nСледующий согласуемый шаг: сначала заменить 9 маршрутов проверенными кандидатами. Для остальных сгруппировать спрос по фактическому общему дорожному коридору и доступной стороне парковки; проверить связность тротуара до существующей зебры. Где непрерывный сухой подход отсутствует либо на пересекаемой дороге вообще нет зебры, выбирать дополнительный переход из реального спроса парковка–дверь, с проверкой обоих берегов, коллизий и входов. Не рисовать зебры автоматически в каждой текущей точке пересечения старого кратчайшего пути.\n\nНапример, у больницы пересечение r4.950 c164.500, L-EA-H-023; ближайшая зебра той же дороги street-crosswalk-39 в 33.4 м, но физический обход к ней не найден. Нужен непрерывный сухой подход либо отдельный проверенный переход у общественного входа. У eastside_stepped_apartment_v1-003 ближайшая по прямой street-crosswalk-43 пересекает другую улицу: на L-EA-V-032 зебр нет. В старом городе несколько домов разделяют одно пересечение: L-OL-H-010 r5.730 c61.500 обслуживает 022, 011, 001, что даёт один общий спрос, а не три новых перехода.\n\n| Здание (префикс REBUILD-VISUAL-) | Немаркированные пересечения, native r/c | Ближайшая зебра на той же дороге | Альтернатива |\n|---|---|---|---|\n${reportRows.join('\n')}\n\nПроизводственные планы, геометрия и NPC не изменены. Детальные отрезки, берега, дорожные ID, глобальные ближайшие зебры и сервисные переулки сохранены в parking_walk_crossings_raw.json.\n`);
