import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {pathToFileURL} from 'node:url';
import {resolveCityParkingPedestrianAccess,createParkingPedestrianSurface} from '../../assets/maps/city_rebuild_v1/city_parking_pedestrian_routes.mjs';
import {createPedestrianAccessPlan} from '../../assets/maps/city_rebuild_v1/city_pedestrian_access_plan.mjs';
import {createCityRoadDressing} from '../../assets/maps/city_rebuild_v1/city_road_dressing.mjs';
import {markingPolygon} from '../../assets/maps/city_rebuild_v1/city_road_dressing_plan.mjs';
import {createLandscapePlan} from '../../assets/maps/city_rebuild_v1/landscape_plan.mjs';
import {createExplorationRailwayPlan} from '../../assets/maps/city_rebuild_v1/exploration_railway_plan.mjs';
const inspectExisting=process.argv.includes('--existing');const dir='outputs/roads_logical_20260912/',input=process.argv[2]||dir+'integration_candidate_snapshot.json',bytes=fs.readFileSync(input),source=JSON.parse(bytes),topology=JSON.parse(fs.readFileSync('assets/maps/city_rebuild_v1/topology_for_placement.json')),railPlan=createExplorationRailwayPlan({topology,landscape:createLandscapePlan()}),start=performance.now(),result=inspectExisting?{parkingPlan:source.parkingPlan,roadPlan:source.roadPlan,stats:source.parkingPlan.pedestrianAccess.stats}:resolveCityParkingPedestrianAccess({parkingPlan:source.parkingPlan,roadPlan:source.roadPlan,topology,instances:[...source.buildings,...source.authoredDecor],extraBodies:source.decorPlan.colliders,railPlan}),elapsedMs=performance.now()-start;
const parking=result.parkingPlan,roads=result.roadPlan,crossings=[...roads.trafficPlan.crosswalks,...roads.trafficPlan.serviceCrossings],surface=createParkingPedestrianSurface({topology,parkingPlan:parking,crosswalks:crossings}),physical=createPedestrianAccessPlan({topology,instances:[...source.buildings,...source.authoredDecor],extraBodies:[...source.decorPlan.colliders,...roads.colliders,...parking.colliders],railPlan,radius:.38,allowedTiles:[0,8,9,19],buildEntranceField:false}),errors=[];
assert.deepEqual(parking.lots.map(({servedBuildingIds,...l})=>l),source.parkingPlan.lots.map(({servedBuildingIds,...l})=>l));assert.deepEqual(parking.bays,source.parkingPlan.bays);assert.deepEqual(roads.signs.slice(0,source.roadPlan.signs.length),source.roadPlan.signs);assert.deepEqual(roads.markings.filter(m=>source.roadPlan.markings.some(s=>s.id===m.id)&&!['edge','center_dash','lane_dash'].includes(m.kind)),source.roadPlan.markings.filter(m=>!['edge','center_dash','lane_dash'].includes(m.kind)));assert.deepEqual(roads.signals,source.roadPlan.signals);assert.deepEqual(roads.junctionRules,source.roadPlan.junctionRules);assert.deepEqual(roads.trafficPlan.turns,source.roadPlan.trafficPlan.turns);assert.deepEqual(roads.trafficPlan.connections,source.roadPlan.trafficPlan.connections);assert.deepEqual(roads.trafficPlan.crosswalks.slice(0,source.roadPlan.trafficPlan.crosswalks.length),source.roadPlan.trafficPlan.crosswalks);
let samples=0;for(const route of parking.walkingRoutes){let length=0;for(let i=1;i<route.points.length;i++){const a=route.points[i-1],b=route.points[i],d=Math.hypot(b.x-a.x,b.z-a.z),steps=Math.max(1,Math.ceil(d/.16));length+=d;for(let k=0;k<=steps;k++){const x=a.x+(b.x-a.x)*k/steps,z=a.z+(b.z-a.z)*k/steps;samples++;if(!physical.clear(x,z)||!surface.allowsCircle(x,z,.38)){errors.push({buildingId:route.buildingId,segment:i,x,z,physical:physical.clear(x,z),permittedRoadSurface:surface.allowsCircle(x,z,.38)});break}}}if(Math.abs(length+(route.entryApproach?.length||0)-route.distance)>1e-5||route.distance>300)errors.push({buildingId:route.buildingId,reason:'incorrect_distance',length,reported:route.distance});}
const added=crossings.filter(c=>c.kind==='parking_access'||c.kind==='service_access');for(const c of added){if(!c.demand.buildingIds.length||c.signIds.length!==2)errors.push({crosswalkId:c.id,reason:'missing_demand_or_directional_signs'});if(c.kind==='parking_access'&&roads.markings.filter(m=>m.crosswalkId===c.id&&m.kind==='crosswalk').length<3)errors.push({crosswalkId:c.id,reason:'incomplete_paint'});for(const e of c.endpoints)if(!physical.clear(e.x,e.z)||surface.roadAt(e.x,e.z))errors.push({crosswalkId:c.id,reason:'invalid_landing',point:e});}
const overlaps=(a,b)=>[a,b].every(p=>p.every((v,i)=>{const q=p[(i+1)%p.length],x=-(q[1]-v[1]),z=q[0]-v[0],pa=a.map(v=>v[0]*x+v[1]*z),pb=b.map(v=>v[0]*x+v[1]*z);return Math.max(...pa)>Math.min(...pb)+1e-7&&Math.max(...pb)>Math.min(...pa)+1e-7})),paintConflicts=[];
for(const c of added.filter(c=>c.kind==='parking_access')){const a=c.endpoints[0],b=c.endpoints[1],length=Math.hypot(b.x-a.x,b.z-a.z),polygon=markingPolygon({x:(a.x+b.x)/2,z:(a.z+b.z)/2,tx:(b.x-a.x)/length,tz:(b.z-a.z)/length,width:2.5,length});for(const mark of roads.markings.filter(m=>m.crosswalkId!==c.id))if(overlaps(polygon,markingPolygon(mark)))paintConflicts.push({crosswalkId:c.id,existingMarkId:mark.id,kind:mark.kind,approachId:mark.approachId});}
if(paintConflicts.length)errors.push({reason:'overlapping_crossing_control_paint',conflicts:paintConflicts.length});const THREE=await import(pathToFileURL((process.env.MAFIOZI_THREE_VENDOR||'D:/codex_release/artist13_hero_first_DEV_20260907/demo/vendor')+'/build/three.module.js')),draws={};for(const [key,plan]of[['before',source.roadPlan],['after',roads]]){const layer=createCityRoadDressing({THREE,plan});draws[key]={draws:layer.stats.totalDraws,paintDraws:layer.stats.paintDraws,equipmentDraws:layer.stats.equipmentDraws,triangles:layer.stats.triangles};layer.dispose();}
const report={phase:inspectExisting?'integrated_worker_read_only':'production_before_after',status:errors.length?'FAIL':parking.pedestrianAccess.uncovered.length?'PARTIAL_ENTRY_METADATA_PENDING':'PASS',inputSHA256:createHash('sha256').update(bytes).digest('hex'),inputStable:fs.readFileSync(input).equals(bytes),elapsedMs,stats:result.stats,samples,errors,paintConflicts,uncovered:parking.pedestrianAccess.uncovered,draws,originalControlsSignsAndCrosswalksPreserved:true,longitudinalClearanceTrims:result.stats.trimmedLongitudinalMarks,limits:['Full .38m circle versus final collision polygons at <=.16m; topology support and authorised crossing/private-surface union verified.','No GPU renderer or loaded-scene FPS measurement.']};fs.writeFileSync(dir+(inspectExisting?'final_worker_parking_pedestrian_audit.json':'parking_pedestrian_production_audit.json'),JSON.stringify(report,null,2));if(!inspectExisting)fs.writeFileSync(dir+'parking_pedestrian_candidate_snapshot.json',JSON.stringify({...source,parkingPlan:parking,roadPlan:roads},null,2));console.log(JSON.stringify(report,null,2));assert.equal(errors.length,0);
