import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {markingPolygon,markingOverlapsBounds,narrowPassageSignApproaches} from '../../assets/maps/city_rebuild_v1/city_road_dressing_plan.mjs';
import {createNarrowMouthAuditContext,auditNarrowMouthSign} from './narrow_mouth_sign_audit.mjs';
import {createLandscapePlan} from '../../assets/maps/city_rebuild_v1/landscape_plan.mjs';
import {createExplorationRailwayPlan} from '../../assets/maps/city_rebuild_v1/exploration_railway_plan.mjs';
const root=new URL('../../',import.meta.url),out=new URL('outputs/roads_logical_20260912/',root),file=new URL(process.argv[2]||'shared_plan_snapshot.json',out),output=process.argv[3]||'dressing_current78_audit.json',snapshot=JSON.parse(fs.readFileSync(file)),plan=snapshot.roadPlan,parking=snapshot.parkingPlan,buildings=snapshot.buildings;
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),allApproaches=plan.junctionRules.flatMap(j=>j.approaches.map(a=>({...a,junctionId:j.id,complexId:j.complexId}))),active=allApproaches.filter(a=>a.allowedTurnIds.length&&!a.internalJunctionLink),byApproach=new Map(allApproaches.map(a=>[a.id,a])),turns=new Map(plan.trafficPlan.turns.map(t=>[t.id,t])),lanes=new Map(plan.trafficPlan.lanes.map(l=>[l.id,l]));
const counts=list=>Object.fromEntries([...new Set(list)].sort().map(key=>[key,list.filter(x=>x===key).length]));
const checked={signFaces:0,footprintMarkPairs:0,footprintPolePairs:0,arrows:0,accessMarkPairs:0},errors=[],review=[];
const narrowSignApproaches=new Map((plan.trafficPlan.narrowPassages||[]).flatMap(p=>narrowPassageSignApproaches(p).map(a=>[p.id+':'+a.kind,{id:a.approachId,outward:a.outward,controlCenter:a.point}])));
const topology=JSON.parse(fs.readFileSync(new URL('assets/maps/city_rebuild_v1/topology_for_placement.json',root))),narrowContext=createNarrowMouthAuditContext(snapshot,topology,createExplorationRailwayPlan({topology,landscape:createLandscapePlan()})),narrowMouthChecks=[];
for(const pole of [...plan.signs,...plan.signals]){
 let narrowCheck=null;if(pole.controlPlacement?.mode==='verified_narrow_mouth_verge'){narrowCheck=auditNarrowMouthSign(pole,narrowContext);narrowMouthChecks.push({id:pole.id,...narrowCheck});if(!narrowCheck.valid)errors.push({kind:'invalid-narrow-mouth-verge',id:pole.id,...narrowCheck});}
 const directional=pole.passageId?narrowSignApproaches.get(pole.passageId+':'+pole.kind):null;if(pole.passageId&&!directional)errors.push({kind:'unknown-directional-sign-control',id:pole.id,passageId:pole.passageId});const approach=directional||byApproach.get(pole.approachId);if(approach){checked.signFaces++;const facing=Math.sin(pole.yaw)*approach.outward.x+Math.cos(pole.yaw)*approach.outward.z,right=(pole.x-approach.controlCenter.x)*approach.outward.z-(pole.z-approach.controlCenter.z)*approach.outward.x,verifiedLeft=narrowCheck?narrowCheck.valid&&narrowCheck.side==='left':pole.controlPlacement?.side==='left'&&pole.controlPlacement.rightVergeUnavailable&&pole.controlPlacement.distanceFromJunctionM>0&&pole.controlPlacement.advanceM>=0;if(facing<.95||right<=0&&!verifiedLeft)errors.push({kind:'pole-facing-or-side',id:pole.id,approachId:approach.id,facing,right});}
 for(const b of buildings)for(const r of [b.footprint,b.entryCorridor].filter(Boolean)){checked.footprintPolePairs++;if(pole.x+.65>r.minC*4.1&&pole.x-.65<r.maxC*4.1&&pole.z+.65>r.minR*4.1&&pole.z-.65<r.maxR*4.1)errors.push({kind:'pole-blocks-building',id:pole.id,buildingId:b.id,x:pole.x,z:pole.z});}
}
for(const mark of plan.markings){
 for(const b of buildings){checked.footprintMarkPairs++;if(markingOverlapsBounds(mark,{minX:b.footprint.minC*4.1,maxX:b.footprint.maxC*4.1,minZ:b.footprint.minR*4.1,maxZ:b.footprint.maxR*4.1}))errors.push({kind:'paint-under-building',id:mark.id,buildingId:b.id,x:mark.x,z:mark.z});}
 if(['edge','center_dash','lane_dash'].includes(mark.kind))for(const access of parking.accessKeepouts){checked.accessMarkPairs++;if(markingOverlapsBounds(mark,access))errors.push({kind:'stripe-crosses-parking-access',id:mark.id,accessId:access.id,x:mark.x,z:mark.z});}
 if(mark.kind==='arrow_shaft'){
  checked.arrows++;const lane=lanes.get(mark.laneId);if(!lane||lane.tx*mark.tx+lane.tz*mark.tz<.94)errors.push({kind:'arrow-wrong-direction',id:mark.id,laneId:mark.laneId,x:mark.x,z:mark.z});
  if(!mark.allowedTurnIds?.length||mark.allowedTurnIds.some(id=>!turns.has(id)||turns.get(id).fromLaneId!==mark.laneId))errors.push({kind:'arrow-unavailable-turn',id:mark.id,laneId:mark.laneId,x:mark.x,z:mark.z});
 }
}
// Diagnose unsigned approaches where only opposite-facing nearby signs exist,
// separately from explicit failures to find a safe physical verge.
const priorityDirectionGaps=[],priorityNoVerge=[];
for(const a of active.filter(a=>a.rule==='priority'&&!a.signId)){
 if(a.prioritySignPlacement?.mode==='no_safe_verge'){priorityNoVerge.push({approachId:a.id,roadId:a.roadId,x:a.controlCenter.x,z:a.controlCenter.z,outward:a.outward});continue;}
 const nearby=plan.signs.filter(s=>s.kind==='priority'&&s.roadId===a.roadId&&distance(s,a.controlCenter)<180),facing=s=>Math.sin(s.yaw)*a.outward.x+Math.cos(s.yaw)*a.outward.z;
 if(nearby.length&&!nearby.some(s=>facing(s)>.8)){const nearest=nearby.sort((s1,s2)=>distance(s1,a.controlCenter)-distance(s2,a.controlCenter))[0];priorityDirectionGaps.push({approachId:a.id,junctionId:a.junctionId,roadId:a.roadId,x:a.controlCenter.x,z:a.controlCenter.z,outward:a.outward,suppressingSign:{id:nearest.id,x:nearest.x,z:nearest.z,yaw:nearest.yaw,facingDot:facing(nearest),distance:distance(nearest,a.controlCenter)}});}
}
const nearbyRepeatedSigns=[];
for(let i=0;i<plan.signs.length;i++)for(let j=i+1;j<plan.signs.length;j++){const a=plan.signs[i],b=plan.signs[j],d=distance(a,b);if(a.kind===b.kind&&a.roadId===b.roadId&&Math.cos(a.yaw-b.yaw)>.98&&d<8)nearbyRepeatedSigns.push({a:a.id,b:b.id,kind:a.kind,roadId:a.roadId,distance:d,positions:[[a.x,a.z],[b.x,b.z]],junctions:[a.junctionId,b.junctionId]});}
const polygons=plan.markings.map(markingPolygon),area=p=>Math.abs(p.reduce((sum,a,i)=>{const b=p[(i+1)%p.length];return sum+a[0]*b[1]-a[1]*b[0]},0))/2;
function intersectPoly(subject,clip){let result=subject;const sign=Math.sign(clip.reduce((sum,a,i)=>{const b=clip[(i+1)%clip.length];return sum+a[0]*b[1]-a[1]*b[0]},0));for(let k=0;k<clip.length&&result.length;k++){const a=clip[k],b=clip[(k+1)%clip.length],edge=p=>sign*((b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0])),next=[];for(let i=0;i<result.length;i++){const p=result[i],q=result[(i+1)%result.length],ep=edge(p),eq=edge(q);if(ep>=-1e-8)next.push(p);if((ep>=0)!==(eq>=0)){const t=ep/(ep-eq);next.push([p[0]+(q[0]-p[0])*t,p[1]+(q[1]-p[1])*t]);}}result=next;}return result;}
const bins=new Map(),overlapPairs=[],seen=new Set();
for(let i=0;i<plan.markings.length;i++){const m=plan.markings[i];if(!['edge','center_dash','lane_dash'].includes(m.kind))continue;const p=polygons[i];for(let x=Math.floor(Math.min(...p.map(v=>v[0]))/8);x<=Math.floor(Math.max(...p.map(v=>v[0]))/8);x++)for(let z=Math.floor(Math.min(...p.map(v=>v[1]))/8);z<=Math.floor(Math.max(...p.map(v=>v[1]))/8);z++){const key=x+','+z;if(!bins.has(key))bins.set(key,[]);for(const j of bins.get(key)){if(seen.has(j+','+i))continue;seen.add(j+','+i);const other=plan.markings[j];if(m.roadId===other.roadId)continue;const overlapArea=area(intersectPoly(p,polygons[j])),ratio=overlapArea/Math.min(m.width*m.length,other.width*other.length);if(ratio>.25)overlapPairs.push({a:other.id,b:m.id,kinds:[other.kind,m.kind],roads:[other.roadId,m.roadId],x:m.x,z:m.z,overlapArea,smallerFraction:ratio,directionDot:other.tx*m.tx+other.tz*m.tz});}bins.get(key).push(i);}}
const yieldTriangles=[];
for(const a of active.filter(a=>a.yieldIndication==='painted_triangle')){
 const edges=plan.markings.filter(m=>m.approachId===a.id&&m.kind==='yield_triangle');if(edges.length!==3){errors.push({kind:'partial-yield-triangle',approachId:a.id,edges:edges.map(e=>e.id)});continue;}
 const center={x:edges.reduce((sum,e)=>sum+e.x,0)/3,z:edges.reduce((sum,e)=>sum+e.z,0)/3},dx=center.x-a.stopPoint.x,dz=center.z-a.stopPoint.z,behind=dx*a.outward.x+dz*a.outward.z,lateral=dx*a.outward.z-dz*a.outward.x;
 const otherJunctions=plan.trafficPlan.allJunctions.filter(j=>j.id!==a.junctionId&&plan.junctionRules.find(n=>n.id===j.id)?.complexId!==a.complexId&&distance(j,center)<j.radius).map(j=>({id:j.id,distance:distance(j,center),radius:j.radius}));
 if(otherJunctions.length)yieldTriangles.push({approachId:a.id,roadId:a.roadId,ids:edges.map(e=>e.id),center,behindStop:behind,lateral,otherJunctions});
 if(behind<-.1)errors.push({kind:'yield-triangle-past-stop',approachId:a.id,center,behind});
}
if(priorityDirectionGaps.length)review.push({id:'ROAD-PRIORITY-DIRECTION-DEDUP',count:priorityDirectionGaps.length,description:'An unsigned priority approach is within the 180 m suppression radius of priority signs that all face another direction.'});
if(priorityNoVerge.length)review.push({id:'ROAD-PRIORITY-NO-SAFE-VERGE',count:priorityNoVerge.length,description:'An eligible priority approach was tried explicitly, but no safe pole verge was found. This is a physical placement gap, not opposite-facing dedup.'});
if(nearbyRepeatedSigns.length)review.push({id:'ROAD-REPEATED-NEAR-SIGNS',count:nearbyRepeatedSigns.length,description:'Same road/kind/facing signs are less than eight metres apart; inspect junction identity before removing anything.'});
if(overlapPairs.length)review.push({id:'ROAD-OVERLAPPING-LONGITUDINAL-MARKS',count:overlapPairs.length,description:'Different authored roads put longitudinal paint polygons over more than25% of the smaller mark.'});
if(yieldTriangles.length)review.push({id:'ROAD-YIELD-PAINT-IN-OTHER-JUNCTION',count:yieldTriangles.length,description:'A fallback yield triangle falls inside a distinct intersection complex footprint; inspect ownership before accepting it.'});
const report={status:errors.length?'CURRENT78_AUDIT_ERRORS':review.length?'CURRENT78_AUDIT_WITH_SEMANTIC_REVIEW':'PASS',readOnly:true,sharedSnapshot:{path:'outputs/roads_logical_20260912/shared_plan_snapshot.json',sha256:createHash('sha256').update(fs.readFileSync(file)).digest('hex'),createdAt:snapshot.createdAt,sourceStable:snapshot.sourceStable},buildings:buildings.length,sourceManifest:snapshot.sourceManifest,counts:{...plan.stats,parking:parking.stats,markKinds:counts(plan.markings.map(m=>m.kind)),signKinds:counts(plan.signs.map(s=>s.kind))},checked,errors,review,priorityDirectionGaps,nearbyRepeatedSigns,overlapPairs,yieldTriangles,unresolvedPlacement:plan.placementUnresolved,limits:['Rendering defects are reported separately in renderer_readonly_report.json.','Review findings are concrete candidates for semantic correction, not permissions to delete content or alter the lane graph.','No GPU scene or authoritative vehicle AI was run.']};
report.priorityNoVerge=priorityNoVerge;report.narrowMouthChecks=narrowMouthChecks;report.sharedSnapshot.path=file.pathname;fs.writeFileSync(new URL(output,out),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,counts:report.counts,errors:errors.slice(0,8),review,narrowMouthChecks,priorityDirectionExamples:priorityDirectionGaps.slice(0,5),overlapExamples:overlapPairs.slice(0,5),yieldExamples:yieldTriangles.slice(0,3)},null,2));if(errors.length)process.exitCode=1;
