import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {createPedestrianAccessPlan} from '../../assets/maps/city_rebuild_v1/city_pedestrian_access_plan.mjs';
import {createLandscapePlan} from '../../assets/maps/city_rebuild_v1/landscape_plan.mjs';
import {createExplorationRailwayPlan} from '../../assets/maps/city_rebuild_v1/exploration_railway_plan.mjs';
import {roadPedestrianPhase,roadSignalPhase} from '../../assets/maps/city_rebuild_v1/city_road_dressing_plan.mjs';
import {createParkingPedestrianSurface} from '../../assets/maps/city_rebuild_v1/city_parking_pedestrian_routes.mjs';

const out='outputs/roads_logical_20260912/',input=out+(process.argv[2]||'integration_candidate_snapshot.json'),bytes=fs.readFileSync(input),snapshot=JSON.parse(bytes),topology=JSON.parse(fs.readFileSync('assets/maps/city_rebuild_v1/topology_for_placement.json')),railPlan=createExplorationRailwayPlan({topology,landscape:createLandscapePlan()}),start=performance.now();
const options={topology,instances:[...snapshot.buildings,...snapshot.authoredDecor],extraBodies:[...snapshot.decorPlan.colliders,...snapshot.roadPlan.colliders,...snapshot.parkingPlan.colliders],railPlan},access=createPedestrianAccessPlan(options),physical=createPedestrianAccessPlan({...options,allowedTiles:[0,8,9,19],buildEntranceField:false}),buildMs=performance.now()-start,checks=[],errors=[],plan=snapshot.roadPlan.trafficPlan,approaches=new Map(snapshot.roadPlan.junctionRules.flatMap(j=>j.approaches.map(a=>[a.id,{...a,junctionId:j.id}])));
const privateSurface=createParkingPedestrianSurface({topology,parkingPlan:snapshot.parkingPlan,crosswalks:[]}),demandAccess=createPedestrianAccessPlan({...options,allowedTiles:[0,8,9,19],surfaceAllowsCircle:privateSurface.allowsCircle,surfaceAllowsSegment:privateSurface.allowsSegment,buildEntranceField:false,step:4.1/5});
for(const crossing of [...plan.crosswalks,...(plan.serviceCrossings||[])]){
 const isDemand=['parking_access','service_access'].includes(crossing.kind),a=approaches.get(crossing.approachId),field=isDemand?demandAccess:access,endpoints=crossing.endpoints.map(p=>({point:p,dryWalkable:field.clear(p.x,p.z),route:access.routeToEntrance(p),sidewalk:field.sidewalkCorridor(p)})),storedRouteFailures=[];
 for(const [i,landing]of(crossing.walkingAccess||[]).entries()){const route=landing.sidewalk;if(endpoints[i].sidewalk||route?.kind!=='crossing_connector')continue;const target=[...plan.crosswalks,...(plan.serviceCrossings||[])].find(c=>c.id===route.nextCrosswalkId),first=route.points[0],last=route.points.at(-1);if(target&&Math.hypot(first.x-endpoints[i].point.x,first.z-endpoints[i].point.z)<.01&&target.endpoints.some(p=>Math.hypot(p.x-last.x,p.z-last.z)<.01)&&route.points.slice(1).every((p,k)=>field.segmentClear(route.points[k],p)))endpoints[i].sidewalk=route;}
 for(const [side,landing]of(crossing.walkingAccess||[]).entries())for(const kind of ['doorRoute','sidewalk']){const route=landing[kind];for(let i=1;i<(route?.points.length||0);i++)if(!field.segmentClear(route.points[i-1],route.points[i])){storedRouteFailures.push({side,kind,segment:i,from:route.points[i-1],to:route.points[i]});break;}}
 const stopBeforeZebraMetres=a?(a.stopPoint.x-crossing.center.x)*crossing.tx+(a.stopPoint.z-crossing.center.z)*crossing.tz-1.25:Math.min(...(crossing.stopControls||[]).map(c=>c.distanceBeforeZebraM));
 const routeUsers=(snapshot.parkingPlan.walkingRoutes||[]).filter(r=>r.crosswalkIds?.includes(crossing.id)),phaseFailures=[];let walkSamples=0;
 if(crossing.signalControl){const control=crossing.signalControl;if(!a||snapshot.roadPlan.signals.find(s=>s.id===a.signalId)?.junctionId!==control.junctionId||a.axis!==control.axis||a.offset!==control.offset)phaseFailures.push('controller_identity');for(let time=0;time<44;time+=.25)if(roadPedestrianPhase(crossing,time)==='walk'){walkSamples++;if(roadSignalPhase(time,control.axis,control.offset)!=='red')phaseFailures.push('walk_with_green');for(let future=0;future<control.clearanceSeconds;future+=.25)if(roadSignalPhase(time+future,control.axis,control.offset)!=='red'){phaseFailures.push('insufficient_clearance');break;}}if(!walkSamples)phaseFailures.push('no_walk_window');}
 const railFailures=[],left=crossing.endpoints[0],right=crossing.endpoints[1],distance=Math.hypot(right.x-left.x,right.z-left.z),samples=Math.ceil(distance/.25);for(let i=0;i<=samples;i++)for(const lateral of[-1.25,0,1.25]){const p={x:left.x+(right.x-left.x)*i/samples+crossing.tx*lateral,z:left.z+(right.z-left.z)*i/samples+crossing.tz*lateral};if(railPlan.blocksPlacement(p.x,p.z,.15)){railFailures.push(p);break;}}
 const physicalCrossing=physical.segmentClear(left,right),logicalDemand=isDemand?routeUsers.length>0&&crossing.demand?.buildingIds.every(id=>routeUsers.some(r=>r.buildingId===id)):!!a&&endpoints.some(e=>e.route),stopValid=Number.isFinite(stopBeforeZebraMetres)&&stopBeforeZebraMetres>=.5&&(!isDemand||crossing.stopControls?.length===2),valid=endpoints.every(e=>e.dryWalkable&&e.sidewalk)&&physicalCrossing&&logicalDemand&&stopValid&&!storedRouteFailures.length&&!phaseFailures.length&&!railFailures.length;
 const result={id:crossing.id,kind:crossing.kind||'junction',approachId:a?.id,rule:a?.rule,signalId:a?.signalId,signalControl:crossing.signalControl,stopBeforeZebraMetres,endpoints:endpoints.map(e=>({...e,route:e.route&&{buildingId:e.route.buildingId,length:e.route.length},sidewalk:e.sidewalk&&{length:e.sidewalk.length}})),physicalCrossing,parkingRouteUsers:routeUsers.map(r=>r.buildingId),storedRouteFailures,phaseFailures,walkSamples,railFailures};checks.push(result);if(!valid)errors.push({...result,reason:{logicalDemand,stopValid}});
}
const report={status:errors.length?'CROSSWALK_ACCESS_GAPS':'PASS',input,inputSHA256:createHash('sha256').update(bytes).digest('hex'),inputStable:fs.readFileSync(input).equals(bytes),buildMs,totalMs:performance.now()-start,stats:access.stats,crossings:checks.length,directDoorEndpoints:checks.flatMap(c=>c.endpoints).filter(e=>e.route).length,doorLinkedCrossings:checks.filter(c=>c.endpoints.some(e=>e.route)||c.parkingRouteUsers.length).length,storedRouteFailures:checks.flatMap(c=>c.storedRouteFailures.map(f=>({crosswalkId:c.id,...f}))),errors,checks,limits:['Read-only CPU audit; no GPU scene and no source actor movement.','Crossing demand is derived from actual parking routes or a dry route to a building entrance; service accesses remain separately labelled.']};fs.writeFileSync(out+(process.argv[3]||'final_crosswalk_access_audit.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,checks:undefined,errors:errors.map(e=>({id:e.id,reason:e.reason,phaseFailures:e.phaseFailures,storedRouteFailures:e.storedRouteFailures,railFailures:e.railFailures.slice(0,2),physicalCrossing:e.physicalCrossing,endpoints:e.endpoints.map(p=>({dryWalkable:p.dryWalkable,sidewalk:!!p.sidewalk,route:!!p.route}))}))},null,2));if(errors.length)process.exitCode=1;
