import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {planCityParkingAccess} from '../../assets/maps/city_rebuild_v1/city_parking_access.mjs';
import {createRoadEdgeControls,evaluateRoadEdgeControl} from '../../assets/maps/city_rebuild_v1/city_road_edge_controls.mjs';
import {createCityRoadNavigation} from '../../assets/maps/city_rebuild_v1/city_road_navigation.mjs';
import {createDirectedLaneRouter} from '../../assets/maps/city_rebuild_v1/city_directed_lane_router.mjs';
import {carCorners} from '../../assets/maps/city_rebuild_v1/car_drive.mjs';
import {markingPolygon} from '../../assets/maps/city_rebuild_v1/city_road_dressing_plan.mjs';

const dir='outputs/roads_logical_20260912/',file=dir+(process.argv[2]||'parking_pedestrian_candidate_snapshot.json'),bytes=fs.readFileSync(file),snapshot=JSON.parse(bytes),started=performance.now(),topology=JSON.parse(fs.readFileSync('assets/maps/city_rebuild_v1/topology_for_placement.json')),instances=[...snapshot.buildings,...snapshot.authoredDecor],roads=snapshot.roadPlan,parking=snapshot.parkingPlan,access=parking.access?.routes?.length?parking.access:planCityParkingAccess({plan:parking,topology,instances,extraBodies:[...snapshot.decorPlan.colliders,...roads.colliders]}),plan=roads.trafficPlan,crossings=[...plan.crosswalks,...(plan.serviceCrossings||[])],byCrossing=new Map(crossings.map(c=>[c.id,c]));
const edges=access.routes.map(r=>{const cumulative=[0];for(let i=1;i<r.points.length;i++)cumulative.push(cumulative.at(-1)+Math.hypot(r.points[i].x-r.points[i-1].x,r.points[i].z-r.points[i-1].z));return {...r,edgeKind:'connection',cumulative};}),index=createRoadEdgeControls(edges,crossings,null,plan.railCrossings||[]),at=(e,s)=>{s=Math.max(0,Math.min(e.cumulative.at(-1),s));let i=1;while(i<e.cumulative.length-1&&e.cumulative[i]<s)i++;const p=e.points[i-1],q=e.points[i],t=(s-e.cumulative[i-1])/(e.cumulative[i]-e.cumulative[i-1]||1);return {x:p.x+(q.x-p.x)*t,z:p.z+(q.z-p.z)*t};},hits=[];
for(const edge of edges)for(const c of index.byEdge.get(edge.id)||[])for(const id of c.crosswalkIds){const crossing=byCrossing.get(id);hits.push({accessRouteId:edge.id,lotId:edge.lotId,kind:edge.kind,gear:edge.gear,crosswalkId:id,crossingKind:crossing.kind||'junction',roadId:crossing.roadId,position:at(edge,c.crossingProgressM),crossingProgressM:c.crossingProgressM,requiredStopProgressM:c.progressM,canonicalIfRegistered:!evaluateRoadEdgeControl(index,c,{occupiedCrosswalkIds:[id]}).allowed});}
const overlap=(a,b)=>[a,b].every(p=>p.every((v,i)=>{const q=p[(i+1)%p.length],x=-(q[1]-v[1]),z=q[0]-v[0],aa=a.map(v=>v[0]*x+v[1]*z),bb=b.map(v=>v[0]*x+v[1]*z);return Math.max(...aa)>=Math.min(...bb)&&Math.max(...bb)>=Math.min(...aa);}));
const graphEdges=(plan.connections||[]).map(e=>{const cumulative=[0];for(let i=1;i<e.points.length;i++)cumulative.push(cumulative.at(-1)+Math.hypot(e.points[i].x-e.points[i-1].x,e.points[i].z-e.points[i-1].z));return {...e,cumulative,edgeKind:'connection'};}),serviceIndex=createRoadEdgeControls(graphEdges,plan.serviceCrossings||[]),serviceChecks=[];
for(const c of plan.serviceCrossings||[]){const [a,b]=c.endpoints,l=Math.hypot(b.x-a.x,b.z-a.z),band=markingPolygon({x:(a.x+b.x)/2,z:(a.z+b.z)/2,tx:(b.x-a.x)/l,tz:(b.z-a.z)/l,length:l,width:2.5}),bodyTouches=[];let poses=0;
 for(const edge of edges){if(!edge.points.some(p=>Math.hypot(p.x-c.center.x,p.z-c.center.z)<l/2+8))continue;let found=null;for(let i=1;i<edge.points.length&&!found;i++){const p=edge.points[i-1],q=edge.points[i],n=Math.max(1,Math.ceil(Math.hypot(q.x-p.x,q.z-p.z)/.15)),dyaw=Math.atan2(Math.sin(q.yaw-p.yaw),Math.cos(q.yaw-p.yaw));for(let k=0;k<=n;k++){const t=k/n,pose={x:p.x+(q.x-p.x)*t,z:p.z+(q.z-p.z)*t,yaw:p.yaw+dyaw*t};poses++;if(overlap(carCorners(pose.x,pose.z,pose.yaw),band)){found=pose;break;}}}if(found)bodyTouches.push({accessRouteId:edge.id,...found});}
 serviceChecks.push({id:c.id,roadId:c.roadId,center:c.center,drivewayCenterHits:hits.filter(h=>h.crosswalkId===c.id).length,fullSedanSamplePoses:poses,drivewayBodyTouches:bodyTouches,graphConnectionControls:[...serviceIndex.byId.values()].filter(control=>control.crosswalkIds.includes(c.id)).map(control=>({edgeId:control.edgeId,id:control.id,occupiedDenied:!evaluateRoadEdgeControl(serviceIndex,control,{occupiedCrosswalkIds:[c.id]}).allowed}))});
}
// Isolate wrapper assembly without recompiling the city graph, while retaining
// the actual router's canonical external-path registration and evaluator.
const canonicalRouter=(p=plan)=>createDirectedLaneRouter({plan:{junctions:[],junctionRules:[],lanes:[],turns:[],connections:[],crosswalks:p.crosswalks||[],serviceCrossings:p.serviceCrossings||[],railCrossings:p.railCrossings||[]},isRoad:()=>true,poseAllowed:()=>true}),dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),length=points=>points.slice(1).reduce((n,p,i)=>n+dist(p,points[i]),0),same=(a,b)=>!!a&&!!b&&dist(a,b)<1e-6;
function pointAlong(points,s){s=Math.max(0,s);for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],d=dist(a,b);if(s<=d){const t=d?s/d:0;return {x:a.x+(b.x-a.x)*t,z:a.z+(b.z-a.z)*t};}s-=d;}return points.at(-1);}
const errors=[],registryChecks=[],registry=canonicalRouter();
function decisions(router,c,id){return {clearAllowed:!!c&&router.evaluateControl(c,{}).allowed===true,occupiedDenied:!!c&&router.evaluateControl(c,{occupiedCrosswalkIds:[id]}).allowed===false,forgedIdDenied:!!c&&router.evaluateControl({...c,id:'forged-id'},{}).allowed===false,tamperedPayloadStillDenied:!!c&&router.evaluateControl({...c,crosswalkIds:[]},{occupiedCrosswalkIds:[id]}).allowed===false};}
for(const hit of hits){const edge=edges.find(e=>e.id===hit.accessRouteId),controls=registry.registerExternalPathControls({id:edge.id,points:edge.points}),control=controls.find(c=>c.crosswalkIds.includes(hit.crosswalkId)),row={accessRouteId:edge.id,crosswalkId:hit.crosswalkId,canonicalPresent:!!control,...decisions(registry,control,hit.crosswalkId)};registryChecks.push(row);if(Object.values(row).some(v=>v===false))errors.push({kind:'external_registry_failure',...row});}
const wrapperExamples=[];
for(const hit of hits.filter(h=>h.kind==='entry')){
 const entry=access.routes.find(r=>r.id===hit.accessRouteId),origin=entry.points[0],canonical=canonicalRouter(),nav=createCityRoadNavigation({getRoadPlan:()=>roads,getParkingPlan:()=>({...parking,access:{...access,routes:[entry]}}),getInstances:()=>instances,isRoad:()=>true,poseAllowed:()=>true,createRouter:()=>({...canonical,route({from,to}){const ready=same(from,to);return {status:ready?'ready':'blocked',points:ready?[{...from}]:[],controls:[],distanceM:0};}})}),result=nav.route({from:origin,to:{...entry.points.at(-1),lotId:entry.lotId}}),control=result.controls?.find(c=>c.crosswalkIds?.includes(hit.crosswalkId)),sourceControl=control&&{...control,stopPoint:{r:control.stopPoint.z/4.1,c:control.stopPoint.x/4.1}},occupied=sourceControl&&nav.query({mode:'road-rules',control:sourceControl,occupiedCrosswalkIds:[hit.crosswalkId]}),clear=sourceControl&&nav.query({mode:'road-rules',control:sourceControl,occupiedCrosswalkIds:[]});
 const expectedRequested=hit.requiredStopProgressM,row={accessRouteId:entry.id,crosswalkId:hit.crosswalkId,status:result.status,actualTailAppended:result.status==='ready'&&result.points.length===entry.points.length,routeControlCount:result.controls?.length,canonicalCrosswalkPresent:!!control,...decisions(canonical,control,hit.crosswalkId),nativeOccupiedDenied:occupied?.control?.allowed===false,nativeClearAllowed:clear?.control?.allowed===true,stopMatchesAssembled:!!control&&Math.abs(control.requestedDistanceM-expectedRequested)<1e-6&&same(control.stopPoint,pointAlong(result.points,expectedRequested)),startInsideApproachCorrect:!!control&&control.startInsideApproach===(expectedRequested<0)};wrapperExamples.push(row);if(result.status!=='ready'||Object.values(row).some(v=>v===false))errors.push({kind:'actual_tail_wrapper_failure',...row});
}
// Two controlled assembly regressions deliberately use small synthetic graph
// sections. They test interpolation across a corner and across the parking /
// graph boundary, not vehicle feasibility on an invented city street.
const upstreamProjectionChecks=[];
const negative=hits.find(h=>h.kind==='entry'&&h.requiredStopProgressM<0);
if(negative){const entry=access.routes.find(r=>r.id===negative.accessRouteId),end=entry.points[0],next=entry.points[1],d=dist(end,next),tx=(next.x-end.x)/d,tz=(next.z-end.z)/d,corner={x:end.x-tx,z:end.z-tz,yaw:end.yaw},origin={x:corner.x-tz*20,z:corner.z+tx*20,yaw:end.yaw},upstream=[origin,corner,end],canonical=canonicalRouter(),isolatedParking={...parking,lots:[parking.lots.find(l=>l.id===entry.lotId)],access:{...access,routes:[entry]}},nav=createCityRoadNavigation({getRoadPlan:()=>roads,getParkingPlan:()=>isolatedParking,getInstances:()=>instances,isRoad:()=>true,poseAllowed:()=>true,createRouter:()=>({...canonical,route:({from,to})=>({status:same(from,origin)&&same(to,end)?'ready':'blocked',points:upstream,controls:[],distanceM:length(upstream)})})}),result=nav.route({from:origin,to:{...entry.points.at(-1),lotId:entry.lotId}}),c=result.controls?.find(c=>c.crosswalkIds?.includes(negative.crosswalkId)),requested=length(upstream)+negative.requiredStopProgressM,expected=pointAlong(upstream,requested),row={scenario:'bent_graph_before_actual_entry_tail',accessRouteId:entry.id,crosswalkId:negative.crosswalkId,status:result.status,requestedDistanceM:c?.requestedDistanceM,expectedRequestedDistanceM:requested,stopPoint:c?.stopPoint,expectedStopPoint:expected,correct:!!c&&Math.abs(c.requestedDistanceM-requested)<1e-6&&same(c.stopPoint,expected)&&c.startInsideApproach===false&&requested<length(upstream)-1};upstreamProjectionChecks.push(row);if(!row.correct)errors.push({kind:'tail_upstream_projection',...row});}
{
 const crossing={id:'qa-prefix-crossing',roadStart:{x:22,z:-3},roadEnd:{x:22,z:3}},toyPlan={crosswalks:[crossing]},canonical=canonicalRouter(toyPlan),graph=[{x:20,z:0,yaw:Math.PI/2},{x:30,z:0,yaw:Math.PI/2},{x:40,z:0,yaw:Math.PI/2}],graphControl=canonical.registerExternalPathControls({id:'qa-graph',points:graph})[0],lot={id:'qa-lot',rect:{minX:10,maxX:20,minZ:-3,maxZ:3}},exit={id:'qa-exit',lotId:lot.id,kind:'exit',gear:'forward',points:[{x:12,z:0,yaw:Math.PI/2},{x:20,z:0,yaw:Math.PI/2}]},nav=createCityRoadNavigation({getRoadPlan:()=>({trafficPlan:toyPlan}),getParkingPlan:()=>({lots:[lot],access:{routes:[exit]}}),getInstances:()=>[],isRoad:()=>true,poseAllowed:()=>true,createRouter:()=>({...canonical,route:()=>({status:'ready',points:graph,controls:[{...graphControl,distanceM:0,requestedDistanceM:graphControl.progressM,stopPoint:graph[0],startInsideApproach:true}],distanceM:20})})}),result=nav.route({from:exit.points[0],to:graph.at(-1)}),c=result.controls?.find(c=>c.crosswalkIds?.includes(crossing.id)),expectedRequested=8+graphControl.progressM,row={scenario:'negative_graph_control_moves_into_parking_prefix',status:result.status,requestedDistanceM:c?.requestedDistanceM,expectedRequestedDistanceM:expectedRequested,stopPoint:c?.stopPoint,expectedStopPoint:{x:12+expectedRequested,z:0},correct:!!c&&Math.abs(c.requestedDistanceM-expectedRequested)<1e-6&&same(c.stopPoint,{x:12+expectedRequested,z:0})&&c.startInsideApproach===false};upstreamProjectionChecks.push(row);if(!row.correct)errors.push({kind:'graph_stop_in_parking_prefix',...row});
}
const sourceFiles=['city_road_navigation.mjs','city_directed_lane_router.mjs','city_road_edge_controls.mjs'],sourceManifest=sourceFiles.map(file=>({file,sha256:createHash('sha256').update(fs.readFileSync('assets/maps/city_rebuild_v1/'+file)).digest('hex')})),report={status:errors.length?'FAIL_CANONICAL_DRIVEWAY_CONTROLS':'PASS',input:file,inputSHA256:createHash('sha256').update(bytes).digest('hex'),inputStable:fs.readFileSync(file).equals(bytes),elapsedMs:performance.now()-started,accessSource:parking.access?.routes?.length?'serialized_actual_access':'current_physical_access_planner_on_final_poles',sourceManifest,counts:{accessRoutes:access.routes.length,hits:hits.length,distinctCrossings:new Set(hits.map(h=>h.crosswalkId)).size,public:hits.filter(h=>h.crossingKind!=='service_access').length,service:hits.filter(h=>h.crossingKind==='service_access').length},errors,hits,serviceChecks,registryChecks,wrapperExamples,upstreamProjectionChecks,limits:['Real external-path registration/evaluation and real-wrapper assembly; graph adapters isolate assembly and do not claim full city connectivity or static vehicle validation.','The two explicitly labelled upstream regressions use controlled synthetic graph sections. Actual driveway points remain unchanged.','No renderer, worker rebuild, GPU scene or source actor movement.','Final worker parking augment can add routes and must repeat this geometric coverage check.']};fs.writeFileSync(dir+'driveway_crossing_control_audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(errors.length)process.exitCode=1;
