import fs from 'node:fs';
import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
import {createLandscapePlan} from '../../assets/maps/city_rebuild_v1/landscape_plan.mjs';
import {createExplorationRailwayPlan} from '../../assets/maps/city_rebuild_v1/exploration_railway_plan.mjs';
import {createCityRoadDressingPlan,narrowPassageSignApproaches} from '../../assets/maps/city_rebuild_v1/city_road_dressing_plan.mjs';
import {explorationKeepouts} from '../../assets/maps/city_rebuild_v1/exploration_scene_support.mjs';
import {createCarWorld,carFits} from '../../assets/maps/city_rebuild_v1/car_drive.mjs';
import {createPedestrianAccessPlan} from '../../assets/maps/city_rebuild_v1/city_pedestrian_access_plan.mjs';
const bytes=fs.readFileSync('outputs/roads_logical_20260912/integration_candidate_snapshot.json'),s=JSON.parse(bytes),topology=JSON.parse(fs.readFileSync('assets/maps/city_rebuild_v1/topology_for_placement.json')),instances=[...s.buildings,...s.authoredDecor],landscape=createLandscapePlan(),railPlan=createExplorationRailwayPlan({landscape,topology}),start=performance.now(),road=createCityRoadDressingPlan({topology,landscape,railPlan,instances,keepouts:[...explorationKeepouts(instances),...explorationKeepouts([{collision:{worldBodies:s.decorPlan.colliders}}]),...s.parkingPlan.keepouts],accessKeepouts:s.parkingPlan.accessKeepouts,pedestrianBodies:[...s.decorPlan.colliders,...s.parkingPlan.colliders]}),buildMs=performance.now()-start;
assert.deepEqual(road.placementUnresolved,[]);assert.deepEqual(road.signals,s.roadPlan.signals,'existing lights preserve placement and control');
let unchangedPoles=0;for(const sign of road.signs.filter(s=>!s.passageId)){assert.deepEqual(sign,s.roadPlan.signs.find(old=>old.id===sign.id));unchangedPoles++;}
const narrow=road.trafficPlan.narrowPassages[0],signs=road.signs.filter(s=>s.passageId===narrow.id);assert.equal(signs.length,2);
for(const expected of narrowPassageSignApproaches(narrow)){const sign=signs.find(s=>s.kind===expected.kind);assert(sign);assert(Math.sin(sign.yaw)*expected.outward.x+Math.cos(sign.yaw)*expected.outward.z>.999);assert(road.colliders.some(b=>b.id===sign.id));for(let i=0;i<32;i++){const x=sign.x+Math.cos(i/32*Math.PI*2)*.2,z=sign.z+Math.sin(i/32*Math.PI*2)*.2,r=Math.floor(z/4.1),c=Math.floor(x/4.1);assert([8,9].includes(topology.grid[r]?.[c]));assert(!topology.roadMask[r]?.[c]&&!topology.protectedMask[r]?.[c]&&!topology.policeMask[r]?.[c]);}}
const oneWay=signs.find(s=>s.kind==='one_way');assert.equal(oneWay.controlPlacement.mode,'verified_narrow_mouth_verge');assert(Math.abs(oneWay.controlPlacement.advanceM)<=2);assert(oneWay.controlPlacement.curbSetbackM<=3);
const oldNoEntry=s.roadPlan.signs.find(s=>s.passageId===narrow.id&&s.kind==='no_entry'),noEntry=signs.find(s=>s.kind==='no_entry');for(const k of['x','z','yaw'])assert.equal(noEntry[k],oldNoEntry[k]);
const allBodies=instances.flatMap(i=>i.collision?.worldBodies||[]).concat(s.decorPlan.colliders,road.colliders,s.parkingPlan.colliders),asphalt=(x,z)=>{const r=Math.floor(z/4.1),c=Math.floor(x/4.1);return topology.grid[r]?.[c]===0&&!!topology.roadMask[r]?.[c]&&!topology.policeMask[r]?.[c]&&!topology.protectedMask[r]?.[c]},world=createCarWorld(topology,allBodies,4.1,{surfaceAt:asphalt});let bodySamples=0;
for(let i=1;i<narrow.points.length;i++){const a=narrow.points[i-1],b=narrow.points[i],steps=Math.ceil(Math.hypot(b.x-a.x,b.z-a.z)/.02),yawDelta=Math.atan2(Math.sin(b.yaw-a.yaw),Math.cos(b.yaw-a.yaw));for(let n=0;n<=steps;n++){const t=n/steps;bodySamples++;assert(carFits(a.x+(b.x-a.x)*t,a.z+(b.z-a.z)*t,a.yaw+yawDelta*t,world));}}
const pedestrian=createPedestrianAccessPlan({topology,instances,extraBodies:[...s.decorPlan.colliders,...road.colliders,...s.parkingPlan.colliders],railPlan,buildEntranceField:false});let pedestrianSegments=0;
for(const crossing of road.trafficPlan.crosswalks)for(const access of crossing.walkingAccess)for(const route of[access.doorRoute,access.sidewalk].filter(Boolean))for(let i=1;i<route.points.length;i++){assert(pedestrian.segmentClear(route.points[i-1],route.points[i]),crossing.id+' continuation clears final poles');pedestrianSegments++;}
assert(fs.readFileSync('outputs/roads_logical_20260912/integration_candidate_snapshot.json').equals(bytes));
const report={status:'PASS',createdAt:new Date().toISOString(),scope:'Fresh dressing with existing final placement/parking/decor snapshot; no full worker or GPU.',buildMs,unchangedPoles,unchangedSignals:road.signals.length,signs,bodySamples,pedestrianSegments,placementUnresolved:road.placementUnresolved,limits:'Final combined worker/pedestrian parking postpass and LIVE are parent-owned.'};fs.writeFileSync('outputs/roads_logical_20260912/narrow_sign_fallback_audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
