import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {resolveCityParkingPedestrianAccess as after} from '../../assets/maps/city_rebuild_v1/city_parking_pedestrian_routes.mjs';
import {createLandscapePlan} from '../../assets/maps/city_rebuild_v1/landscape_plan.mjs';
import {createExplorationRailwayPlan} from '../../assets/maps/city_rebuild_v1/exploration_railway_plan.mjs';
const base=new URL('../../assets/maps/city_rebuild_v1/',import.meta.url),out=new URL('../../outputs/roads_logical_20260912/',import.meta.url),input=process.argv[2]||new URL('integration_candidate_snapshot.json',out),bytes=fs.readFileSync(input),snapshot=JSON.parse(bytes),topology=JSON.parse(fs.readFileSync(new URL('topology_for_placement.json',base))),railPlan=createExplorationRailwayPlan({topology,landscape:createLandscapePlan()}),options={parkingPlan:snapshot.parkingPlan,roadPlan:snapshot.roadPlan,topology,instances:[...snapshot.buildings,...snapshot.authoredDecor],extraBodies:snapshot.decorPlan.colliders,railPlan},asData=source=>'data:text/javascript;base64,'+Buffer.from(source).toString('base64'),absoluteImports=source=>source.replace(/from '\.\/([^']+)'/g,(_,file)=>"from '"+new URL(file,base).href+"'");
const pedestrianSource=fs.readFileSync(new URL('city_pedestrian_access_plan.mjs',base),'utf8'),uncached=pedestrianSource.replace(/function gridEdgeClear\(index,next,p,q\)\{[^\n]+/, 'function gridEdgeClear(index,next,p,q){return segmentClear(p,q);}');assert.notEqual(uncached,pedestrianSource);
const helperSource=fs.readFileSync(new URL('city_parking_pedestrian_routes.mjs',base),'utf8'),beforeSource=absoluteImports(helperSource).replace(new URL('city_pedestrian_access_plan.mjs',base).href,asData(uncached)),{resolveCityParkingPedestrianAccess:before}=await import(asData(beforeSource));
const files=['city_parking_pedestrian_routes.mjs','city_pedestrian_access_plan.mjs','tower_public_approach.mjs'],hash=file=>createHash('sha256').update(fs.readFileSync(new URL(file,base))).digest('hex'),manifest=files.map(file=>({file,sha256:hash(file)})),timings={before:[],after:[]};let expected=null;
for(let iteration=0;iteration<4;iteration++)for(const name of iteration%2?['after','before']:['before','after']){const start=performance.now(),result=(name==='before'?before:after)(options),elapsed=performance.now()-start;if(iteration)timings[name].push(elapsed);const serialized=JSON.stringify(result);if(expected===null)expected=serialized;else assert.equal(serialized,expected,'cache must preserve every route, crossing, sign, marking and metadata');process.stdout.write(JSON.stringify({iteration,name,ms:elapsed,served:result.stats.servedBuildings})+'\n');}
const quantiles=values=>{values.sort((a,b)=>a-b);return {p50:values[1],p95:values[2],samples:values.length}},report={status:'PASS_EQUIVALENT_LOGIC_AND_GEOMETRY',scenario:'Same populated78 snapshot, 39lots/59bays/46targets. Four alternating pairs, first warmup; only exact grid-edge collision-cache differs.',inputKind:snapshot.parkingPlan.pedestrianAccess?'already_integrated':'raw_before_pedestrian_postpass',sourceManifest:manifest,sourceStable:manifest.every(f=>hash(f.file)===f.sha256),inputSHA256:createHash('sha256').update(bytes).digest('hex'),beforeMs:quantiles(timings.before),afterMs:quantiles(timings.after),allOutputEquivalent:true,scope:'One worker-time post-pass. No per-frame logic, GPU scene or FPS claim.'};fs.writeFileSync(new URL('parking_pedestrian_cpu_comparison.json',out),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));assert(report.sourceStable);
