import fs from 'node:fs';
import {performance} from 'node:perf_hooks';
import {CITY_ROAD_ROUTES} from '../../assets/maps/city_rebuild_v1/city_road_dressing_routes.mjs';
import {findIncomingControlVerge} from '../../assets/maps/city_rebuild_v1/city_road_dressing_plan.mjs';
import {createLandscapePlan} from '../../assets/maps/city_rebuild_v1/landscape_plan.mjs';
import {createExplorationRailwayPlan} from '../../assets/maps/city_rebuild_v1/exploration_railway_plan.mjs';
import {explorationKeepouts} from '../../assets/maps/city_rebuild_v1/exploration_scene_support.mjs';
const started=performance.now(),s=JSON.parse(fs.readFileSync('outputs/roads_logical_20260912/integration_candidate_snapshot.json')),topology=JSON.parse(fs.readFileSync('assets/maps/city_rebuild_v1/topology_for_placement.json')),rail=createExplorationRailwayPlan({topology,landscape:createLandscapePlan()}),roads=s.roadPlan,instances=[...s.buildings,...s.authoredDecor],reserved=[...explorationKeepouts(instances),...explorationKeepouts([{collision:{worldBodies:s.decorPlan.colliders}}]),...s.parkingPlan.keepouts,...roads.accessKeepouts],cell=(x,z)=>({r:Math.floor(z/4.1),c:Math.floor(x/4.1)}),landings=roads.trafficPlan.crosswalks.flatMap(c=>c.endpoints),poles=[...roads.signs,...roads.signals],report=[];
function reject(x,z){if(rail.blocksPlacement(x,z,1.35))return 'rail';if(landings.some(p=>Math.hypot(p.x-x,p.z-z)<1.05))return 'landing';for(let i=0;i<9;i++){const a=i*Math.PI/4,px=x+(i===8?0:Math.cos(a)*.2),pz=z+(i===8?0:Math.sin(a)*.2),q=cell(px,pz);if(![8,9].includes(topology.grid[q.r]?.[q.c])||topology.roadMask[q.r]?.[q.c]||topology.protectedMask?.[q.r]?.[q.c]||topology.policeMask?.[q.r]?.[q.c])return 'terrain';}if(reserved.some(b=>x+.65>b.minX&&x-.65<b.maxX&&z+.65>b.minZ&&z-.65<b.maxZ))return 'reserved';if(poles.some(p=>Math.hypot(p.x-x,p.z-z)<1.5))return 'pole';return null;}
for(const failure of roads.placementUnresolved){const junction=roads.junctionRules.find(j=>j.approaches.some(a=>a.id===failure.approachId)),a=junction.approaches.find(a=>a.id===failure.approachId),road=CITY_ROAD_ROUTES.find(r=>r.id===a.roadId),fragment=Number(a.id.split(':').at(-2)),direction=Number(a.id.split(':').at(-1)),points=road.fragments[fragment].map(([x,z])=>({x:x*4.1,z:z*4.1})),segments=[];let length=0;for(let i=1;i<points.length;i++){const p=points[i-1],q=points[i],d=Math.hypot(q.x-p.x,q.z-p.z);segments.push({a:p,b:q,start:length,length:d,tx:(q.x-p.x)/d,tz:(q.z-p.z)/d});length+=d;}
 const sample=s=>{const e=segments.find(e=>e.start+e.length>=s)||segments.at(-1),t=Math.max(0,Math.min(1,(s-e.start)/e.length));return {x:e.a.x+(e.b.x-e.a.x)*t,z:e.a.z+(e.b.z-e.a.z)*t,tx:e.tx,tz:e.tz};},project=p=>segments.map(e=>{const along=Math.max(0,Math.min(e.length,(p.x-e.a.x)*e.tx+(p.z-e.a.z)*e.tz));return {progress:e.start+along,d:Math.hypot(p.x-e.a.x-e.tx*along,p.z-e.a.z-e.tz*along)}}).sort((a,b)=>a.d-b.d)[0].progress,progress=project(junction),entryDistance=Math.abs(project(a.controlCenter)-progress),upstream=roads.trafficPlan.allJunctions.find(j=>j.id===a.nextJunctionId),upstreamDistance=upstream?Math.abs(project(upstream)-progress)-entryDistance:Infinity,approach={...a,pathId:road.id+':'+fragment,path:{length,segments,sample},direction,progress,entryDistance},reasons={},candidates=[];
 const surfaceAt=(x,z)=>{const p=cell(x,z),road=!!topology.roadMask[p.r]?.[p.c];return {road,land:[8,9].includes(topology.grid[p.r]?.[p.c])&&!road};};
 const position=findIncomingControlVerge({approach,upstreamDistance,surfaceAt,safeSign(x,z){const reason=reject(x,z);reasons[reason||'valid']=(reasons[reason||'valid']||0)+1;return !reason;}});
 for(let along=-8;along<=32;along+=.5){const center=sample(progress+direction*(entryDistance+along)),out={x:center.tx*direction,z:center.tz*direction};for(const side of[-1,1])for(let lateral=road.width/2;lateral<=18;lateral+=.4){const x=center.x+out.z*lateral*side,z=center.z-out.x*lateral*side;if(!reject(x,z))candidates.push({x,z,along,lateral,side,railDistance:rail.distanceToTrack(x,z)});}}
 const railwayFallback=position||!rail.blocksPlacement(a.controlCenter.x,a.controlCenter.z,1.35)?null:findIncomingControlVerge({approach,upstreamDistance,surfaceAt,safeSign:(x,z)=>!reject(x,z),maxCurbSetback:6});
 report.push({failure,entryDistance,upstreamDistance,position,railwayFallback,reasons,nearbyFreeCandidates:candidates.sort((a,b)=>Math.hypot(a.along,a.lateral)-Math.hypot(b.along,b.lateral)).slice(0,12)});
}
const output={elapsedMs:performance.now()-started,report};fs.writeFileSync('outputs/roads_logical_20260912/unresolved_control_probe.json',JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));
