import fs from 'node:fs';
import {createCityRoadDressingPlan} from '../../assets/maps/city_rebuild_v1/city_road_dressing_plan.mjs';
import {createLandscapePlan} from '../../assets/maps/city_rebuild_v1/landscape_plan.mjs';
import {createExplorationRailwayPlan} from '../../assets/maps/city_rebuild_v1/exploration_railway_plan.mjs';
import {explorationKeepouts} from '../../assets/maps/city_rebuild_v1/exploration_scene_support.mjs';
const base='assets/maps/city_rebuild_v1/',dir='outputs/roads_logical_20260912/',snapshot=JSON.parse(fs.readFileSync(dir+'shared_plan_snapshot.json')),topology=JSON.parse(fs.readFileSync(base+'topology_for_placement.json')),instances=[...snapshot.buildings,...snapshot.authoredDecor],landscape=createLandscapePlan(),railPlan=createExplorationRailwayPlan({topology,landscape}),keepouts=[...explorationKeepouts(instances),...explorationKeepouts([{collision:{worldBodies:snapshot.decorPlan.colliders}}]),...snapshot.parkingPlan.keepouts];
const plan=createCityRoadDressingPlan({topology,landscape,railPlan,keepouts,accessKeepouts:snapshot.parkingPlan.accessKeepouts,instances,pedestrianBodies:[...snapshot.decorPlan.colliders,...snapshot.parkingPlan.colliders]}),approaches=plan.junctionRules.flatMap(j=>j.approaches),wanted=approaches.filter(a=>a.allowedTurnIds.length&&!a.internalJunctionLink&&(a.prioritySignPlacement?.mode==='no_safe_verge'||a.yieldIndication==='unresolved'));
const report=wanted.map(a=>{const positions=[];for(let along=-12;along<=48;along+=.5)for(let side=-20;side<=20;side+=.5){if(Math.abs(side)<1)continue;const x=a.controlCenter.x+a.outward.x*along+a.outward.z*side,z=a.controlCenter.z+a.outward.z*along-a.outward.x*side;if(plan.safeSign(x,z))positions.push({x,z,along,side,distance:Math.hypot(along,side)});}positions.sort((a,b)=>a.distance-b.distance);return {id:a.id,rule:a.rule,center:a.controlCenter,width:a.width,outward:a.outward,stop:a.stopPoint,rightBefore:positions.filter(p=>p.side>0&&p.along>=0).slice(0,5),leftBefore:positions.filter(p=>p.side<0&&p.along>=0).slice(0,5),all:positions.slice(0,5)}});
fs.writeFileSync(dir+'control_verge_probe.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
