import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {createCityRoadDressingPlan} from '../../assets/maps/city_rebuild_v1/city_road_dressing_plan.mjs';
import {createLandscapePlan} from '../../assets/maps/city_rebuild_v1/landscape_plan.mjs';
import {createExplorationRailwayPlan} from '../../assets/maps/city_rebuild_v1/exploration_railway_plan.mjs';
import {explorationKeepouts} from '../../assets/maps/city_rebuild_v1/exploration_scene_support.mjs';

const base='assets/maps/city_rebuild_v1/',out='outputs/roads_logical_20260912/',input=process.argv[2]||out+'shared_plan_snapshot.json',output=process.argv[3]||out+'dressing_candidate_snapshot.json';
const snapshot=JSON.parse(fs.readFileSync(input)),topology=JSON.parse(fs.readFileSync(base+'topology_for_placement.json')),instances=[...snapshot.buildings,...snapshot.authoredDecor],landscape=createLandscapePlan(),railPlan=createExplorationRailwayPlan({topology,landscape}),keepouts=[...explorationKeepouts(instances),...explorationKeepouts([{collision:{worldBodies:snapshot.decorPlan.colliders}}]),...snapshot.parkingPlan.keepouts];
const files=['city_road_dressing_plan.mjs','city_road_traffic_plan.mjs','city_road_dressing_routes.mjs','car_drive.mjs'],hash=file=>createHash('sha256').update(fs.readFileSync(base+file)).digest('hex'),manifest=files.map(file=>({file:base+file,sha256:hash(file)}));
const start=performance.now(),{isRoad,paintSafe,safeSign,...roadPlan}=createCityRoadDressingPlan({topology,landscape,railPlan,keepouts,accessKeepouts:snapshot.parkingPlan.accessKeepouts,instances,pedestrianBodies:[...snapshot.decorPlan.colliders,...snapshot.parkingPlan.colliders]});
const elapsed=performance.now()-start,after=manifest.map((row,i)=>({...row,afterSHA256:hash(files[i])})),result={...snapshot,createdAt:new Date().toISOString(),roadPlan,roadRebuildMs:elapsed,sourceManifest:after,sourceStable:after.every(r=>r.sha256===r.afterSHA256),scope:'Reused exact shared78 buildings/decor/parking reservations; only the road planner is rebuilt, no grass or GPU scene.'};
fs.writeFileSync(output,JSON.stringify(result));const possiblePoles=roadPlan.placementUnresolved.map(row=>{const a=roadPlan.junctionRules.flatMap(j=>j.approaches).find(a=>a.id===row.approachId),candidates=[];for(let along=-8;along<=12;along+=.5)for(let side=1;side<=a.width/2+8;side+=.5){const x=a.controlCenter.x+a.outward.x*along+a.outward.z*side,z=a.controlCenter.z+a.outward.z*along-a.outward.x*side;if(safeSign(x,z))candidates.push({x,z,along,side,distance:Math.hypot(along,side)});}candidates.sort((a,b)=>a.distance-b.distance);return {...row,control:a.controlCenter,width:a.width,outward:a.outward,closest:candidates.slice(0,5)};});fs.writeFileSync(output.replace('.json','.pole_diagnostics.json'),JSON.stringify(possiblePoles,null,2));console.log(JSON.stringify({output,sourceStable:result.sourceStable,roadRebuildMs:elapsed,stats:roadPlan.stats,unresolved:roadPlan.placementUnresolved,possiblePoles},null,2));
