import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { createCityRoadDressing } from '../../assets/maps/city_rebuild_v1/city_road_dressing.mjs';

const root=new URL('../../',import.meta.url),out=new URL('outputs/roads_logical_20260912/',root);fs.mkdirSync(out,{recursive:true});
const vendor=process.env.MAFIOZI_THREE_VENDOR||'D:/codex_release/artist13_hero_first_DEV_20260907/demo/vendor';
const T=await import(pathToFileURL(vendor+'/build/three.module.js'));
const plan={markings:[{id:'probe-paint',kind:'center_dash',x:0,z:0,y:.036,tx:0,tz:1,width:.13,length:3.1,color:'white'}],signs:['yield','priority','speed','crosswalk','rail'].map((kind,i)=>({id:'probe-'+kind,kind,x:i*4,y:0,z:0,yaw:0,direction:1})),signals:[0,1].map((axis,i)=>({id:'probe-signal-'+axis,kind:'traffic_signal',x:24+i*4,y:0,z:0,yaw:i*Math.PI/2,axis,offset:0})),stats:{}};
const road=createCityRoadDressing({THREE:T,plan}),batches=road.object.children.filter(n=>n.isBatchedMesh),tracked=[];
for(const mesh of batches){for(const [kind,resource]of[['geometry',mesh.geometry],...Object.entries(mesh).filter(([,value])=>value?.isTexture)]){const record={mesh:mesh.name,kind,disposed:0};resource.addEventListener('dispose',()=>record.disposed++);tracked.push(record);}}
const geometryChecks=[];for(const mesh of road.object.children){if(mesh.name.startsWith('RoadPaint:')){let minY=Infinity;for(let i=0;i<mesh.geometry.attributes.normal.count;i++)minY=Math.min(minY,mesh.geometry.attributes.normal.getY(i));geometryChecks.push({kind:'paint-upward-normals',minimum:minY,pass:minY>.99});}}
const before={...road.stats};road.update(0,{time:0,focus:{x:10000,z:10000}});const farVisible=road.object.children.filter(n=>n.visible).map(n=>({name:n.name,isInstancedMesh:!!n.isInstancedMesh,frustumCulled:n.frustumCulled}));
road.dispose();const firstDispose=tracked.map(r=>({...r}));road.dispose();
const report={status:'READ_ONLY_RENDERER_DEFECTS_CONFIRMED',source:{path:'assets/maps/city_rebuild_v1/city_road_dressing.mjs',sha256:createHash('sha256').update(fs.readFileSync(new URL('assets/maps/city_rebuild_v1/city_road_dressing.mjs',root))).digest('hex')},scenario:'CPU Three constructor, five sign types, two traffic heads; no renderer/GPU created',baseline:before,geometryChecks,farVisible,resourceDisposal:firstDispose,secondDispose:tracked,findings:[{id:'ROAD-RENDER-LIFECYCLE',severity:'P1',evidence:'BatchedMesh geometry and data textures do not receive disposal when the road layer is cleared.',affected:batches.map(n=>n.name),expectedResources:tracked.length,disposedResources:firstDispose.filter(r=>r.disposed).length},{id:'ROAD-RENDER-ORPHAN-BULBS',severity:'P2',evidence:'At a 10 km focus all road equipment is culled but every TrafficBulbs mesh stays visible with frustumCulled=false.',affected:farVisible.filter(n=>n.name.startsWith('TrafficBulbs:')).map(n=>n.name)}],implementationChanged:false,limitations:['No visual or frame-time acceptance; the findings are resource/visibility contract checks.','The synthetic IDs isolate renderer behaviour; shared current78 IDs are analysed in the separate road audit.']};
fs.writeFileSync(new URL('renderer_readonly_report.json',out),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,batches:batches.length,expectedResources:tracked.length,disposedResources:report.findings[0].disposedResources,farVisible},null,2));
